"""
Parser for the AD-Miner data JSON file (data_<render_name>_<date>.json).

This file is generated by AD-Miner and embedded in its output ZIP. It contains:
  - general_statistic : nb_domains, nb_dc, nb_da, nb_users, nb_groups, nb_computers, nb_adcs
  - value             : 60+ indicator counters (kerberoastables, dangerous_paths, etc.)
  - color_category    : risk color per indicator (red/orange/yellow/green/grey)
  - render_name       : report title
  - datetime          : report date string
"""
import json
import os

# ── Severity mapping from AD-Miner color to internal severity ─────────────────
_COLOR_TO_SEV = {
    "red":    "CRITICAL",
    "orange": "HIGH",
    "yellow": "MEDIUM",
    "green":  "INFO",
    "grey":   None,   # skip
}

# ── Human-readable titles, descriptions, category and remediation steps per indicator key ─────
# Format: (title, description, category, remediation_steps)
# remediation_steps is a list of dicts: {step, priority, icon, title, detail, commands: [{label, code}]}
_INDICATOR_META = {
    # RED - Immediate risk
    "dc_impersonation": (
        "DC Impersonation (Shadow Credentials)",
        "Domain Controllers vulnerable to shadow credentials attacks, allowing impersonation.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "critical", "icon": "bi-search", "title": "Identify affected Domain Controllers",
             "detail": "List DCs with unauthorized msDS-KeyCredentialLink attributes set.",
             "commands": [{"label": "PowerShell (RSAT)", "code": "Get-ADComputer -Filter {PrimaryGroupID -eq 516} -Properties msDS-KeyCredentialLink | Where-Object {$_.msDS-KeyCredentialLink} | Select-Object Name, msDS-KeyCredentialLink"}]},
            {"step": 2, "priority": "critical", "icon": "bi-trash3", "title": "Remove unauthorized Shadow Credentials",
             "detail": "Clear the msDS-KeyCredentialLink attribute on affected DCs unless explicitly configured via Windows Hello for Business.",
             "commands": [{"label": "PowerShell", "code": "Set-ADComputer -Identity <DC_NAME> -Clear msDS-KeyCredentialLink"}]},
            {"step": 3, "priority": "normal", "icon": "bi-shield-lock", "title": "Enable Protected Users and credential guard",
             "detail": "Add DC machine accounts to the Protected Users group and enable Credential Guard to prevent credential extraction.",
             "commands": []},
        ]
    ),
    "up_to_date_admincount": (
        "Inadequate AdminCount Settings",
        "Objects with AdminCount=1 that should not have it, or vice versa.",
        "Permissions",
        [
            {"step": 1, "priority": "critical", "icon": "bi-search", "title": "Enumerate objects with incorrect AdminCount",
             "detail": "Find non-privileged accounts or groups with AdminCount=1 that are no longer members of protected groups.",
             "commands": [{"label": "PowerShell", "code": 'Get-ADObject -Filter {AdminCount -eq 1} -Properties AdminCount,MemberOf | Where-Object {$_.objectClass -eq "user"} | Select-Object Name, DistinguishedName'}]},
            {"step": 2, "priority": "critical", "icon": "bi-pencil-square", "title": "Reset AdminCount and restore inheritance",
             "detail": "Reset AdminCount to 0 and restore permission inheritance on objects that should not be protected.",
             "commands": [{"label": "PowerShell", "code": "Set-ADObject -Identity <DN> -Replace @{AdminCount=0}\n# Restore ACL inheritance via ADSI:\n$acl = Get-Acl 'AD:<DN>'; $acl.SetAccessRuleProtection($false, $true); Set-Acl 'AD:<DN>' $acl"}]},
            {"step": 3, "priority": "normal", "icon": "bi-arrow-repeat", "title": "Let SDProp reprocess AdminSDHolder",
             "detail": "SDProp runs every 60 minutes and will propagate the correct ACL to protected objects. You can force it manually.",
             "commands": [{"label": "PowerShell (force SDProp)", "code": "Invoke-Command -ComputerName <PDC> { $fixup = [adsi]'LDAP://CN=Directory Service,CN=Windows NT,CN=Services,CN=Configuration,DC=domain,DC=com'; $fixup.Put('fixupInheritance', 1); $fixup.SetInfo() }"}]},
        ]
    ),
    "dangerous_paths": (
        "Dangerous Attack Paths",
        "Attack paths leading to high-value targets (Domain Admins, DCs, etc.).",
        "Attack Paths",
        [
            {"step": 1, "priority": "critical", "icon": "bi-binoculars", "title": "Review attack paths in BloodHound/AD-Miner",
             "detail": "Use the AD-Miner interactive graph to identify the shortest paths from regular users to Domain Admins. Focus on GenericAll, WriteDACL, and Owns edges.",
             "commands": []},
            {"step": 2, "priority": "critical", "icon": "bi-scissors", "title": "Break the most critical path segments",
             "detail": "Remove dangerous ACEs on the objects identified in the paths. Prioritize edges leading directly to DCs and privileged groups.",
             "commands": [{"label": "PowerShell — remove a specific ACE", "code": "$acl = Get-Acl 'AD:CN=target,DC=domain,DC=com'\n$ace = $acl.Access | Where-Object {$_.IdentityReference -eq 'DOMAIN\\user' -and $_.ActiveDirectoryRights -match 'GenericAll'}\n$acl.RemoveAccessRule($ace)\nSet-Acl 'AD:CN=target,DC=domain,DC=com' $acl"}]},
            {"step": 3, "priority": "normal", "icon": "bi-people", "title": "Auditer et r\u00e9duire les membres de tous les groupes Tier 0",
             "detail": "\u00c9num\u00e9rer chaque groupe privil\u00e9gi\u00e9 et questionner chaque membre. Les comptes de service ne doivent jamais \u00eatre DA/EA. Objectif : moins de 5 comptes DA au total.",
             "commands": [{"label": "PowerShell \u2014 audit complet des groupes Tier 0", "code": "@('Domain Admins','Enterprise Admins','Schema Admins','Group Policy Creator Owners','DnsAdmins','Administrators','Account Operators','Backup Operators','Print Operators','Server Operators') | ForEach-Object {\n    $grp = $_\n    Get-ADGroupMember -Identity $grp -Recursive -ErrorAction SilentlyContinue | Select-Object @{N='Group';E={$grp}}, Name, SamAccountName, objectClass, DistinguishedName\n} | Export-Csv tier0_audit.csv -NoTypeInformation\nWrite-Host 'Export\u00e9 dans tier0_audit.csv'"}]},
            {"step": 4, "priority": "normal", "icon": "bi-shield-check", "title": "Appliquer le mod\u00e8le de Tiering AD par GPO",
             "detail": "Bloquer les cr\u00e9dentiels Tier 0 sur les machines Tier 1/2 via des GPO de refus de connexion. Lier une GPO \u00e0 l'OU Servers ET \u00e0 l'OU Workstations qui interdit explicitement la connexion des DA/EA.",
             "commands": [{"label": "GPO \u2014 User Rights Assignment (refus DA/EA Tier 1 & 2)", "code": "# Chemin GPO (Computer Configuration > Policies > Windows Settings >\n#   Security Settings > Local Policies > User Rights Assignment) :\n#\n#   Deny log on locally                     -> ajouter : Domain Admins, Enterprise Admins, Schema Admins\n#   Deny log on through Remote Desktop      -> ajouter : Domain Admins, Enterprise Admins, Schema Admins\n#   Deny log on as a batch job              -> ajouter : Domain Admins, Enterprise Admins, Schema Admins\n#   Deny log on as a service               -> ajouter : Domain Admins, Enterprise Admins, Schema Admins\n#\n# V\u00e9rifier la politique effective sur un serveur :\nInvoke-Command -ComputerName <server> {\n    secedit /export /cfg C:\\Temp\\secpol.cfg /areas USER_RIGHTS\n    Get-Content C:\\Temp\\secpol.cfg | Select-String 'SeDeny'"}]}
        ],
    ),
    "can_dcsync": (
        "DCSync Privilege",
        "Non-DC accounts with replication rights allowing DCSync attacks.",
        "Permissions",
        [
            {"step": 1, "priority": "critical", "icon": "bi-search", "title": "Identify accounts with DCSync rights",
             "detail": "Find accounts with DS-Replication-Get-Changes and DS-Replication-Get-Changes-All rights on the domain root.",
             "commands": [{"label": "PowerShell", "code": "(Get-Acl 'AD:DC=domain,DC=com').Access | Where-Object {\n    $_.ObjectType -eq '1131f6aa-9c07-11d1-f79f-00c04fc2dcd2' -or\n    $_.ObjectType -eq '1131f6ab-9c07-11d1-f79f-00c04fc2dcd2'\n} | Select-Object IdentityReference, ActiveDirectoryRights"}]},
            {"step": 2, "priority": "critical", "icon": "bi-x-circle", "title": "Remove replication rights from non-DC accounts",
             "detail": "Only SYSTEM, Domain Controllers, and certain AD sync accounts (e.g. Azure AD Connect) should have these rights.",
             "commands": [{"label": "PowerShell", "code": "$dn = 'DC=domain,DC=com'\n$acl = Get-Acl \"AD:$dn\"\n# Remove the specific ACE (replace <IDENTITY>)\n$ace = $acl.Access | Where-Object {$_.IdentityReference -eq '<IDENTITY>' -and $_.ObjectType -eq '1131f6aa-9c07-11d1-f79f-00c04fc2dcd2'}\n$acl.RemoveAccessRule($ace)\nSet-Acl \"AD:$dn\" $acl"}]},
            {"step": 3, "priority": "normal", "icon": "bi-bell", "title": "Set up monitoring for DCSync activity",
             "detail": "Enable auditing on the domain root and alert on Event ID 4662 with replication GUIDs from non-DC accounts.",
             "commands": []},
        ]
    ),
    "ldap_configuration": (
        "LDAP Servers Configuration",
        "LDAP servers with insecure configuration (unsigned/unsigned LDAP binding).",
        "Network",
        [
            {"step": 1, "priority": "critical", "icon": "bi-shield-fill-exclamation", "title": "Enable LDAP signing on Domain Controllers",
             "detail": "Configure DCs to require LDAP signing. This prevents LDAP relay and man-in-the-middle attacks.",
             "commands": [{"label": "GPO setting (registry)", "code": "# Via GPO: Computer Config > Windows Settings > Security Settings > Local Policies > Security Options\n# 'Domain controller: LDAP server signing requirements' = Require signing\n\n# Or via registry on each DC:\nSet-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\NTDS\\Parameters' -Name 'LDAPServerIntegrity' -Value 2"}]},
            {"step": 2, "priority": "critical", "icon": "bi-lock-fill", "title": "Enable LDAP Channel Binding",
             "detail": "Require LDAP channel binding to prevent LDAP relay attacks. Enable via Group Policy or registry.",
             "commands": [{"label": "Registry", "code": "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\NTDS\\Parameters' -Name 'LdapEnforceChannelBinding' -Value 2"}]},
            {"step": 3, "priority": "normal", "icon": "bi-plug-fill", "title": "Audit LDAP clients for compatibility",
             "detail": "Before enforcing, check for legacy applications that may use unsigned LDAP. Enable Event ID 2886/2887 audit logging to identify them.",
             "commands": [{"label": "Registry — enable LDAP audit logging", "code": "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\NTDS\\Diagnostics' -Name '16 LDAP Interface Events' -Value 2"}]},
        ]
    ),
    "objects_to_operators_member": (
        "Paths to Operators Groups",
        "Objects with a path to built-in operator groups (Backup, Account, Print, etc.).",
        "Attack Paths",
        [
            {"step": 1, "priority": "critical", "icon": "bi-people-fill", "title": "Audit membership of Operator groups",
             "detail": "Review all members of Backup Operators, Account Operators, Print Operators, and Server Operators. These groups have dangerous privileges.",
             "commands": [{"label": "PowerShell", "code": "@('Backup Operators','Account Operators','Print Operators','Server Operators') | ForEach-Object {\n    Write-Host \"=== $_ ===\"\n    Get-ADGroupMember -Identity $_ -Recursive | Select-Object Name, SamAccountName, objectClass\n}"}]},
            {"step": 2, "priority": "critical", "icon": "bi-person-dash", "title": "Remove unauthorized members",
             "detail": "Remove all accounts that do not strictly require membership. These groups are Tier 0 equivalent and should have minimal or no members.",
             "commands": [{"label": "PowerShell", "code": "Remove-ADGroupMember -Identity 'Backup Operators' -Members 'DOMAIN\\user' -Confirm:$false"}]},
            {"step": 3, "priority": "normal", "icon": "bi-diagram-3", "title": "Break attack path segments leading to these groups",
             "detail": "Use BloodHound/AD-Miner to trace which objects have paths to these groups and remove the connecting ACEs.",
             "commands": []},
        ]
    ),
    "graph_path_objects_to_ou_handlers": (
        "Paths to Organizational Units (OU)",
        "Objects that can modify GPOs or OUs affecting privileged accounts.",
        "Attack Paths",
        [
            {"step": 1, "priority": "critical", "icon": "bi-folder2-open", "title": "Audit OU and GPO write permissions",
             "detail": "Identify accounts with WriteDACL, GenericAll, or GPLink permissions on OUs containing privileged accounts.",
             "commands": [{"label": "PowerShell — OU ACL", "code": "Get-GPPermission -All -DomainName domain.com | Where-Object {$_.Permission -eq 'GpoEditDeleteModifySecurity'}"}]},
            {"step": 2, "priority": "critical", "icon": "bi-x-circle", "title": "Supprimer les permissions excessives sur les OUs et GPOs",
             "detail": "D\u00e9l\u00e9guer uniquement le minimum requis. Supprimer les ACE GenericAll/WriteDACL/WriteOwner non h\u00e9rit\u00e9es des comptes non-admins sur les OUs et les objets GPO.",
             "commands": [{"label": "PowerShell \u2014 supprimer WriteDACL/GenericAll sur une OU", "code": "# Remplacer <OU_DN> et <IDENTITY>\n$ouDN     = 'OU=Corp,DC=domain,DC=com'\n$identity = 'DOMAIN\\user_or_group'\n$acl = Get-Acl \"AD:$ouDN\"\n$toRemove = $acl.Access | Where-Object {\n    $_.IdentityReference -eq $identity -and\n    $_.ActiveDirectoryRights -match 'GenericAll|WriteDacl|WriteOwner' -and\n    $_.IsInherited -eq $false\n}\n$toRemove | ForEach-Object { $acl.RemoveAccessRule($_) | Out-Null }\nSet-Acl \"AD:$ouDN\" $acl\n\n# Supprimer les droits d'\u00e9dition GPO :\nSet-GPPermission -Guid '<GPO_GUID>' -TargetName 'DOMAIN\\user' -TargetType User -PermissionLevel None -ErrorAction Stop"}]},
            {"step": 3, "priority": "normal", "icon": "bi-eye", "title": "Enable GPO change auditing",
             "detail": "Audit all changes to Group Policy Objects with Event ID 5136.",
             "commands": []},
        ]
    ),
    "anomaly_acl": (
        "ACL Anomalies",
        "Abnormal or dangerous ACE entries on sensitive AD objects.",
        "Permissions",
        [
            {"step": 1, "priority": "critical", "icon": "bi-search", "title": "Identify dangerous ACEs on sensitive objects",
             "detail": "Use BloodHound/AD-Miner or the following commands to find GenericAll, WriteDACL, WriteOwner on sensitive objects.",
             "commands": [{"label": "PowerShell", "code": "Import-Module ActiveDirectory\nGet-ADObject -Filter {adminCount -eq 1} | ForEach-Object {\n    $acl = Get-Acl \"AD:$($_.DistinguishedName)\"\n    $acl.Access | Where-Object {\n        $_.ActiveDirectoryRights -match 'GenericAll|WriteDacl|WriteOwner'\n        -and $_.AccessControlType -eq 'Allow'\n        -and $_.IsInherited -eq $false\n    } | Select-Object @{N='Object';E={$_}}, IdentityReference, ActiveDirectoryRights\n}"}]},
            {"step": 2, "priority": "critical", "icon": "bi-trash3", "title": "Remove anomalous ACEs",
             "detail": "For each ACE identified, verify if it is legitimate. Remove those that are not.",
             "commands": [{"label": "PowerShell", "code": "$dn = 'CN=target,DC=domain,DC=com'\n$acl = Get-Acl \"AD:$dn\"\n$ace = $acl.Access | Where-Object {$_.IdentityReference -eq 'DOMAIN\\user' -and $_.ActiveDirectoryRights -match 'GenericAll'}\n$acl.RemoveAccessRule($ace)\nSet-Acl \"AD:$dn\" $acl"}]},
            {"step": 3, "priority": "normal", "icon": "bi-clipboard-check", "title": "\u00c9tablir une baseline ACL avec AD ACL Scanner",
             "detail": "Utiliser l'outil AD ACL Scanner de Microsoft pour exporter l'int\u00e9gralit\u00e9 des ACLs AD sous forme de rapport. Ex\u00e9cuter p\u00e9riodiquement et comparer au baseline pour d\u00e9tecter les modifications non autoris\u00e9es.",
             "commands": [{"label": "PowerShell \u2014 baseline ACL sans outil tiers", "code": "# Export baseline des ACLs sur tous les objets privil\u00e9gi\u00e9s (AdminCount=1) :\n$date = Get-Date -Format 'yyyyMMdd'\nGet-ADObject -Filter {adminCount -eq 1} -Properties DistinguishedName |\nForEach-Object {\n    $dn = $_.DistinguishedName\n    (Get-Acl \"AD:$dn\").Access |\n    Select-Object @{N='Object';E={$dn}}, IdentityReference, ActiveDirectoryRights, IsInherited, AccessControlType\n} | Export-Csv \"ACL_baseline_$date.csv\" -NoTypeInformation\nWrite-Host \"Baseline export\u00e9 : ACL_baseline_$date.csv\"\n\n# Comparer baseline N et N-1 :\n$old = Import-Csv 'ACL_baseline_20260101.csv'\n$new = Import-Csv \"ACL_baseline_$date.csv\"\nCompare-Object $old $new -Property Object, IdentityReference, ActiveDirectoryRights | Where-Object { $_.SideIndicator -eq '=>' }"}]},
        ]
    ),
    # ORANGE - Alerts
    "rid_singularities": (
        "RID Singularities",
        "Accounts with suspicious RID values that may indicate legacy or rogue accounts.",
        "Misc",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Identify accounts with abnormal RIDs",
             "detail": "Accounts with RIDs below 1000 are built-in. Accounts with RIDs matching those from other domains may indicate SID injection.",
             "commands": [{"label": "PowerShell", "code": "Get-ADUser -Filter * -Properties SID | Where-Object {($_.SID.Value -split '-')[-1] -lt 1000} | Select-Object Name, SID"}]},
            {"step": 2, "priority": "high", "icon": "bi-question-circle", "title": "Investigate and disable suspicious accounts",
             "detail": "If a non-built-in account has an unusually low or unusual RID, investigate its origin and disable or delete it if illegitimate.",
             "commands": [{"label": "PowerShell", "code": "Disable-ADAccount -Identity <samAccountName>"}]},
        ]
    ),
    "graph_path_objects_to_da": (
        "Paths to Domain Admins",
        "Non-privileged objects with a direct or indirect path to Domain Admin privileges.",
        "Attack Paths",
        [
            {"step": 1, "priority": "high", "icon": "bi-binoculars", "title": "Cartographier les chemins vers les Domain Admins (Cypher)",
             "detail": "Interroger Neo4j (backend BloodHound) pour trouver tous les chemins vers DA. Identifier les n\u0153uds choke-points qui apparaissent dans le plus de chemins.",
             "commands": [{"label": "Cypher \u2014 shortest paths vers Domain Admins", "code": "// Dans le navigateur Neo4j / BloodHound\nMATCH p=shortestPath((u:User {enabled:true})-[*1..]->(g:Group {name:'DOMAIN ADMINS@DOMAIN.COM'}))\nWHERE NOT u.name STARTS WITH 'KRBTGT'\nRETURN p LIMIT 50\n\n// Trouver les choke points (noeuds les plus travers\u00e9s) :\nMATCH p=shortestPath((u:User {enabled:true})-[*1..]->(g:Group {name:'DOMAIN ADMINS@DOMAIN.COM'}))\nUNWIND nodes(p) AS n\nRETURN n.name, count(*) AS occurrences ORDER BY occurrences DESC LIMIT 20"}]},
            {"step": 2, "priority": "high", "icon": "bi-scissors", "title": "Supprimer les ACE permettant l'escalade de privil\u00e8ges",
             "detail": "Pour chaque n\u0153ud interm\u00e9diaire dans le chemin d'attaque, supprimer l'ACE dangereuse (GenericAll, GenericWrite, WriteDACL, WriteOwner, AddMember) qui constitue le maillon de la cha\u00eene.",
             "commands": [{"label": "PowerShell \u2014 supprimer une ACE GenericAll sur un objet cible", "code": "# Remplacer <OBJECT_DN> et <IDENTITY> par les valeurs du chemin d'attaque\n$targetDN = 'CN=TargetUser,OU=Users,DC=domain,DC=com'\n$identity  = 'DOMAIN\\source_user'\n$acl = Get-Acl \"AD:$targetDN\"\n$rulesToRemove = $acl.Access | Where-Object {\n    $_.IdentityReference -eq $identity -and\n    ($_.ActiveDirectoryRights -band [System.DirectoryServices.ActiveDirectoryRights]::GenericAll) -ne 0\n}\n$rulesToRemove | ForEach-Object { $acl.RemoveAccessRule($_) | Out-Null }\nSet-Acl \"AD:$targetDN\" $acl\nWrite-Host \"ACE supprim\u00e9e sur $targetDN\""}]},
            {"step": 3, "priority": "normal", "icon": "bi-people", "title": "Reduce Domain Admins group membership",
             "detail": "Keep Domain Admins membership to an absolute minimum. Use Just-In-Time (JIT) privileged access for administrative tasks.",
             "commands": [{"label": "PowerShell — list DA members", "code": "Get-ADGroupMember -Identity 'Domain Admins' -Recursive | Select-Object Name, SamAccountName, objectClass"}]},
        ]
    ),
    "smb_signing": (
        "SMB Signing Disabled",
        "Computers without SMB signing enabled, vulnerable to relay attacks.",
        "Network",
        [
            {"step": 1, "priority": "high", "icon": "bi-shield-fill-exclamation", "title": "Enable SMB signing via GPO",
             "detail": "Deploy a GPO to require SMB signing on all workstations and servers. This prevents NTLM relay attacks (e.g. Responder, PetitPotam).",
             "commands": [{"label": "GPO path", "code": "Computer Configuration > Policies > Windows Settings > Security Settings > Local Policies > Security Options\n\n'Microsoft network server: Digitally sign communications (always)' = Enabled\n'Microsoft network client: Digitally sign communications (always)' = Enabled"}]},
            {"step": 2, "priority": "normal", "icon": "bi-check2-all", "title": "Verify SMB signing status on all hosts",
             "detail": "Audit all machines to confirm SMB signing is enforced.",
             "commands": [{"label": "PowerShell", "code": "Get-SmbServerConfiguration | Select-Object RequireSecuritySignature, EnableSecuritySignature\n# Or remotely:\nInvoke-Command -ComputerName <host> {Get-SmbServerConfiguration | Select-Object RequireSecuritySignature}"}]},
        ]
    ),
    "privileged_accounts_outside_Protected_Users": (
        "Privileged Accounts Outside Protected Users",
        "Privileged accounts not in the Protected Users group, reducing their protection.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "high", "icon": "bi-shield-plus", "title": "Add privileged accounts to Protected Users group",
             "detail": "All Tier 0 accounts (Domain Admins, Enterprise Admins, Schema Admins, etc.) should be in the Protected Users security group.",
             "commands": [{"label": "PowerShell", "code": "# Add all Domain Admins to Protected Users:\nGet-ADGroupMember 'Domain Admins' | ForEach-Object {\n    Add-ADGroupMember -Identity 'Protected Users' -Members $_.DistinguishedName\n}"}]},
            {"step": 2, "priority": "normal", "icon": "bi-info-circle", "title": "V\u00e9rifier la compatibilit\u00e9 et valider les restrictions Protected Users",
             "detail": "Les membres du groupe Protected Users ne peuvent plus utiliser NTLM, DES, RC4 Kerberos, la d\u00e9l\u00e9gation non contrainte ni les cr\u00e9dentiels mis en cache. Tester sur un compte de staging avant g\u00e9n\u00e9ralisation. Monitorer avec les evenements Kerberos.",
             "commands": [{"label": "PowerShell \u2014 d\u00e9tecter les comptes encore NTLM / RC4 avant ajout", "code": "# Event 4776 = authentification NTLM (DC Security Log) :\nGet-WinEvent -ComputerName <DC> -FilterHashtable @{LogName='Security';Id=4776} -MaxEvents 1000 |\n    ForEach-Object {\n        [xml]$x = $_.ToXml()\n        $user = ($x.Event.EventData.Data | Where-Object Name -eq 'TargetUserName').'#text'\n        [pscustomobject]@{ Time=$_.TimeCreated; User=$user; Type='NTLM' }\n    } | Group-Object User | Sort-Object Count -Descending | Select-Object -First 20 Name, Count\n\n# Event 4769 avec EncryptionType 0x17 = RC4 Kerberos :\nGet-WinEvent -ComputerName <DC> -FilterHashtable @{LogName='Security';Id=4769} -MaxEvents 500 |\n    Where-Object { $_.Message -match '0x17' } |\n    ForEach-Object { [xml]$x = $_.ToXml(); ($x.Event.EventData.Data | Where-Object Name -eq 'ServiceName').'#text' } |\n    Sort-Object -Unique"}]},
        ]
    ),
    "server_users_could_be_admin": (
        "Users Who Could Become Admin on Servers",
        "Non-admin users who could escalate to admin on servers via misconfiguration.",
        "Permissions",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Identifier les permissions mal configur\u00e9es sur les serveurs",
             "detail": "Trouver les droits admin locaux non justifi\u00e9s, les services avec des ex\u00e9cutables modifiables ou des chemins non quot\u00e9s, qui permettent \u00e0 un utilisateur standard d'escalader sur un serveur.",
             "commands": [{"label": "PowerShell \u2014 admins locaux sur tous les serveurs", "code": "$servers = Get-ADComputer -Filter {OperatingSystem -like '*Server*' -and Enabled -eq $true} | Select-Object -ExpandProperty Name\n$results = foreach ($s in $servers) {\n    try {\n        $members = Invoke-Command -ComputerName $s -ScriptBlock {\n            net localgroup Administrators 2>&1\n        } -ErrorAction Stop\n        [pscustomobject]@{Server=$s; Members=($members | Where-Object {$_ -match '\\\\'})}\n    } catch { [pscustomobject]@{Server=$s; Members=\"ERREUR: $_\"} }\n}\n$results | Export-Csv server_localadmins.csv -NoTypeInformation -Encoding UTF8"}, {"label": "PowerShell \u2014 services avec ex\u00e9cutables modifiables", "code": "Get-WmiObject Win32_Service | Where StartMode -ne 'Disabled' | ForEach-Object {\n    $bin = ($_.PathName -replace '\"','').Trim() -split ' ' | Select-Object -First 1\n    if ($bin -and (Test-Path $bin)) {\n        $acl = Get-Acl $bin\n        $acl.Access | Where-Object {\n            $_.FileSystemRights -match 'FullControl|Write|Modify' -and\n            $_.IdentityReference -notmatch 'SYSTEM|Admins|TrustedInstaller|CREATOR'\n        } | Select-Object @{N='Service';E={$_.Name}}, @{N='Binary';E={$bin}}, IdentityReference, FileSystemRights\n    }\n}"}]},
            {"step": 2, "priority": "high", "icon": "bi-x-circle", "title": "Remove unnecessary local admin rights",
             "detail": "Audit local Administrators groups on all servers and remove any non-admin user accounts.",
             "commands": [{"label": "PowerShell (remote)", "code": "Invoke-Command -ComputerName <server> {\n    $members = net localgroup Administrators | Where-Object {$_ -and $_ -notmatch 'Alias|Members|-'}\n    $members\n}"}]},
            {"step": 3, "priority": "normal", "icon": "bi-shield-lock", "title": "Enable Local Admin Password Solution (LAPS)",
             "detail": "Deploy LAPS to randomize local administrator passwords on all servers, preventing lateral movement via pass-the-hash.",
             "commands": []},
        ]
    ),
    "users_admin_of_computers": (
        "Non-Admin Users with Local Admin Rights",
        "Standard users holding local administrator rights on workstations or servers.",
        "Permissions",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Enumerate all local admin assignments",
             "detail": "Audit the local Administrators group on workstations and servers to find non-admin domain accounts.",
             "commands": [{"label": "PowerShell (via GPO Restricted Groups audit)", "code": "# Or use a tool like PingCastle / BloodHound SharpHound\n# On individual machines:\nInvoke-Command -ComputerName <host> { net localgroup Administrators }"}]},
            {"step": 2, "priority": "high", "icon": "bi-person-dash", "title": "Remove non-admin users from local Administrators",
             "detail": "Use GPO Restricted Groups or GPO Preferences to enforce the local Administrators group membership.",
             "commands": [{"label": "GPO path", "code": "Computer Configuration > Preferences > Control Panel Settings > Local Users and Groups\nAction: Update, Group: Administrators\nRemove non-admin members, keep only BUILTIN\\Administrator and designated admin accounts"}]},
            {"step": 3, "priority": "normal", "icon": "bi-laptop", "title": "Deploy LAPS for workstations",
             "detail": "Use Microsoft LAPS v2 (Windows LAPS in Windows Server 2022 / Windows 11) to manage local admin passwords.",
             "commands": []},
        ]
    ),
    # YELLOW - Minor risk
    "computers_without_laps": (
        "Computers Without LAPS",
        "Computers not managed by Local Administrator Password Solution.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "normal", "icon": "bi-download", "title": "Deploy Windows LAPS (v2)",
             "detail": "Windows LAPS is built-in since Windows Server 2022 and Windows 11 22H2. For older systems, use Microsoft LAPS v1.",
             "commands": [{"label": "PowerShell — extend AD schema (LAPS v2)", "code": "# Requires Domain Admin\nUpdate-LapsADSchema\nSet-LapsADComputerSelfPermission -Identity 'OU=Workstations,DC=domain,DC=com'"}]},
            {"step": 2, "priority": "normal", "icon": "bi-gear", "title": "Configure LAPS via GPO",
             "detail": "Create a GPO to enable LAPS and set the password complexity and rotation interval.",
             "commands": [{"label": "GPO path (Windows LAPS)", "code": "Computer Configuration > Administrative Templates > System > LAPS\n- Enable LAPS: Enabled\n- Password Complexity: Large letters + small letters + numbers + special characters\n- Password Age: 30 days"}]},
            {"step": 3, "priority": "normal", "icon": "bi-check2-all", "title": "Verify LAPS deployment",
             "detail": "Confirm that all machines have the LAPS attribute populated in AD.",
             "commands": [{"label": "PowerShell", "code": "Get-ADComputer -Filter * -Properties ms-Mcs-AdmPwdExpirationTime | Where-Object {!$_.'ms-Mcs-AdmPwdExpirationTime'} | Select-Object Name"}]},
        ]
    ),
    "computers_last_connexion": (
        "Stale Computer Accounts",
        "Computer accounts that have not connected in more than 90 days.",
        "Misc",
        [
            {"step": 1, "priority": "normal", "icon": "bi-search", "title": "Identify stale computer accounts",
             "detail": "List computer accounts where lastLogonDate is older than 90 days.",
             "commands": [{"label": "PowerShell", "code": "$cutoff = (Get-Date).AddDays(-90)\nGet-ADComputer -Filter {LastLogonDate -lt $cutoff -and Enabled -eq $true} -Properties LastLogonDate | Select-Object Name, LastLogonDate | Sort-Object LastLogonDate"}]},
            {"step": 2, "priority": "normal", "icon": "bi-ban", "title": "Disable then delete stale accounts",
             "detail": "Disable accounts first to allow time to detect issues, then delete after a grace period (e.g. 30 days).",
             "commands": [{"label": "PowerShell — bulk disable", "code": "$cutoff = (Get-Date).AddDays(-90)\nGet-ADComputer -Filter {LastLogonDate -lt $cutoff -and Enabled -eq $true} | Disable-ADAccount"}]},
        ]
    ),
    "dormants_accounts": (
        "Dormant User Accounts",
        "User accounts inactive for more than 90 days but still enabled.",
        "Misc",
        [
            {"step": 1, "priority": "normal", "icon": "bi-search", "title": "Identify dormant user accounts",
             "detail": "Find user accounts with no logon activity for over 90 days.",
             "commands": [{"label": "PowerShell", "code": "$cutoff = (Get-Date).AddDays(-90)\nGet-ADUser -Filter {LastLogonDate -lt $cutoff -and Enabled -eq $true} -Properties LastLogonDate, Department | Select-Object Name, SamAccountName, LastLogonDate, Department | Sort-Object LastLogonDate"}]},
            {"step": 2, "priority": "normal", "icon": "bi-person-x", "title": "Disable inactive accounts",
             "detail": "Disable dormant accounts after confirming they are not service accounts or shared accounts. Move them to a dedicated OU.",
             "commands": [{"label": "PowerShell", "code": "Disable-ADAccount -Identity <samAccountName>\nMove-ADObject -Identity <DN> -TargetPath 'OU=Disabled,DC=domain,DC=com'"}]},
            {"step": 3, "priority": "normal", "icon": "bi-calendar-check", "title": "Implement automated account lifecycle management",
             "detail": "Create a recurring process (script or IDM tool) to automatically disable accounts after a defined inactivity period.",
             "commands": []},
        ]
    ),
    "never_expires": (
        "Passwords That Never Expire",
        "User accounts with password set to never expire.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "normal", "icon": "bi-search", "title": "List accounts with non-expiring passwords",
             "detail": "Find all user accounts where PasswordNeverExpires is set to True.",
             "commands": [{"label": "PowerShell", "code": "Get-ADUser -Filter {PasswordNeverExpires -eq $true -and Enabled -eq $true} -Properties PasswordNeverExpires, PasswordLastSet | Select-Object Name, SamAccountName, PasswordLastSet | Sort-Object PasswordLastSet"}]},
            {"step": 2, "priority": "normal", "icon": "bi-calendar2-x", "title": "Remove the PasswordNeverExpires flag",
             "detail": "Enforce a password expiration policy. Exceptions should be limited to documented service accounts with strong, unique passwords.",
             "commands": [{"label": "PowerShell — bulk", "code": "Get-ADUser -Filter {PasswordNeverExpires -eq $true} | Set-ADUser -PasswordNeverExpires $false"}]},
            {"step": 3, "priority": "normal", "icon": "bi-lock", "title": "Configure a domain password policy or Fine-Grained Password Policy",
             "detail": "Set a maximum password age of 90 days (or shorter for privileged accounts). Use Fine-Grained Password Policies (FGPP) for service accounts.",
             "commands": [{"label": "PowerShell — set domain default policy", "code": "Set-ADDefaultDomainPasswordPolicy -MaxPasswordAge '90.00:00:00' -Identity 'domain.com'"}]},
        ]
    ),
    "pre_windows_2000_compatible_access_group": (
        "Pre-Windows 2000 Compatible Access Group",
        "Members of the legacy 'Pre-Windows 2000 Compatible Access' group with broad read rights.",
        "Permissions",
        [
            {"step": 1, "priority": "normal", "icon": "bi-search", "title": "Check membership of this legacy group",
             "detail": "This group grants Everyone or Authenticated Users broad read access to AD objects. Membership of 'Everyone' or 'ANONYMOUS LOGON' is critical.",
             "commands": [{"label": "PowerShell", "code": "Get-ADGroupMember -Identity 'Pre-Windows 2000 Compatible Access' | Select-Object Name, objectClass, SID"}]},
            {"step": 2, "priority": "normal", "icon": "bi-person-dash", "title": "Remove 'Everyone' and 'ANONYMOUS LOGON'",
             "detail": "If 'Everyone' or 'ANONYMOUS LOGON' is a member, remove them immediately. This is a legacy setting that should no longer be required.",
             "commands": [{"label": "PowerShell", "code": "Remove-ADGroupMember -Identity 'Pre-Windows 2000 Compatible Access' -Members 'S-1-1-0' -Confirm:$false  # Everyone\nRemove-ADGroupMember -Identity 'Pre-Windows 2000 Compatible Access' -Members 'S-1-5-7' -Confirm:$false  # ANONYMOUS LOGON"}]},
        ]
    ),
    "users_pwd_not_changed_since": (
        "Passwords Not Changed in 1+ Year",
        "User accounts whose password has not been changed for over a year.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "normal", "icon": "bi-search", "title": "Identify accounts with old passwords",
             "detail": "Find users who have not changed their password in more than 365 days.",
             "commands": [{"label": "PowerShell", "code": "$cutoff = (Get-Date).AddDays(-365)\nGet-ADUser -Filter {PasswordLastSet -lt $cutoff -and Enabled -eq $true -and PasswordNeverExpires -eq $false} -Properties PasswordLastSet | Select-Object Name, SamAccountName, PasswordLastSet | Sort-Object PasswordLastSet"}]},
            {"step": 2, "priority": "normal", "icon": "bi-key", "title": "Force password reset at next login",
             "detail": "Force affected users to change their password at next logon.",
             "commands": [{"label": "PowerShell — bulk", "code": "Get-ADUser -Filter {PasswordLastSet -lt $cutoff -and Enabled -eq $true} | Set-ADUser -ChangePasswordAtLogon $true"}]},
            {"step": 3, "priority": "normal", "icon": "bi-envelope", "title": "Notify users and enforce policy",
             "detail": "Send advance notifications before forcing password resets. Implement a domain password policy to automatically expire passwords.",
             "commands": []},
        ]
    ),
    "kerberoastables": (
        "Kerberoastable Accounts",
        "Service accounts with SPNs vulnerable to offline Kerberos ticket cracking.",
        "Kerberos",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Enumerate Kerberoastable accounts",
             "detail": "List all user accounts with Service Principal Names (SPNs) set.",
             "commands": [{"label": "PowerShell", "code": "Get-ADUser -Filter {ServicePrincipalName -ne '$null' -and Enabled -eq $true} -Properties ServicePrincipalName, PasswordLastSet | Select-Object Name, SamAccountName, ServicePrincipalName, PasswordLastSet"}]},
            {"step": 2, "priority": "high", "icon": "bi-star-fill", "title": "Migrate service accounts to gMSA",
             "detail": "Group Managed Service Accounts (gMSA) have 240-character auto-rotating passwords and are immune to Kerberoasting.",
             "commands": [{"label": "PowerShell — create gMSA", "code": "New-ADServiceAccount -Name 'svc_app' -DNSHostName 'svc_app.domain.com' -PrincipalsAllowedToRetrieveManagedPassword 'server$'\nAdd-ADComputerServiceAccount -Identity <server> -ServiceAccount 'svc_app'"}]},
            {"step": 3, "priority": "normal", "icon": "bi-key-fill", "title": "Set strong passwords (if gMSA not possible)",
             "detail": "If gMSA cannot be used, set passwords of at least 30+ random characters and rotate them regularly.",
             "commands": []},
            {"step": 4, "priority": "normal", "icon": "bi-bell", "title": "Monitor for Kerberoasting attempts",
             "detail": "Alert on Event ID 4769 with encryption type 0x17 (RC4) for service ticket requests.",
             "commands": []},
        ]
    ),
    "as_rep": (
        "AS-REP Roastable Accounts",
        "Accounts with Kerberos pre-authentication disabled, vulnerable to AS-REP Roasting.",
        "Kerberos",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Identify accounts without pre-authentication",
             "detail": "Find accounts where DONT_REQUIRE_PREAUTH (0x400000) flag is set.",
             "commands": [{"label": "PowerShell", "code": "Get-ADUser -Filter {DoesNotRequirePreAuth -eq $true -and Enabled -eq $true} -Properties DoesNotRequirePreAuth | Select-Object Name, SamAccountName"}]},
            {"step": 2, "priority": "high", "icon": "bi-toggle-on", "title": "Re-enable Kerberos pre-authentication",
             "detail": "Unless there is a specific and documented reason (legacy app), re-enable pre-authentication on all accounts.",
             "commands": [{"label": "PowerShell — bulk fix", "code": "Get-ADUser -Filter {DoesNotRequirePreAuth -eq $true} | Set-ADAccountControl -DoesNotRequirePreAuth $false"}]},
        ]
    ),
    "non-dc_with_unconstrained_delegations": (
        "Unconstrained Delegation (non-DC)",
        "Non-DC computers configured with unconstrained Kerberos delegation.",
        "Kerberos",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Identify computers with unconstrained delegation",
             "detail": "Find non-DC machines with TrustedForDelegation set.",
             "commands": [{"label": "PowerShell", "code": "Get-ADComputer -Filter {TrustedForDelegation -eq $true} -Properties TrustedForDelegation | Where-Object {$_.Name -notlike '*DC*'} | Select-Object Name, DNSHostName"}]},
            {"step": 2, "priority": "high", "icon": "bi-x-circle", "title": "Remove unconstrained delegation",
             "detail": "Disable unconstrained delegation and replace with constrained or resource-based constrained delegation.",
             "commands": [{"label": "PowerShell", "code": "Set-ADComputer -Identity <computer> -TrustedForDelegation $false"}]},
            {"step": 3, "priority": "normal", "icon": "bi-check2-square", "title": "Remplacer par de la d\u00e9l\u00e9gation contrainte (KCD) ou RBCD",
             "detail": "Configurer the machine avec de la d\u00e9l\u00e9gation contrainte classique (msDS-AllowedToDelegateTo) limit\u00e9e \u00e0 des SPNs sp\u00e9cifiques, ou utiliser RBCD (Resource-Based Constrained Delegation) qui donne le contr\u00f4le au service cible.",
             "commands": [{"label": "PowerShell \u2014 configurer KCD (d\u00e9l\u00e9gation contrainte classique)", "code": "# D\u00e9sactiver la d\u00e9l\u00e9gation non contrainte :\nSet-ADComputer <computer> -TrustedForDelegation $false\n\n# Configurer KCD vers un service sp\u00e9cifique :\nSet-ADComputer <computer> -Add @{'msDS-AllowedToDelegateTo' = 'cifs/<target_server>', 'cifs/<target_server.domain.com>'}\n\n# Configurer RBCD (le serveur cible contr\u00f4le qui peut d\u00e9l\u00e9guer vers lui) :\n$sid = (Get-ADComputer <source_computer>).SID\n$sd  = New-Object Security.AccessControl.RawSecurityDescriptor \"O:BAD:(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;$($sid.Value))\"\n$sdb = New-Object byte[] ($sd.BinaryLength)\n$sd.GetBinaryForm($sdb, 0)\nGet-ADComputer <target_server> | Set-ADObject -Replace @{'msDS-AllowedToActOnBehalfOfOtherIdentity' = $sdb}\nWrite-Host 'RBCD configur\u00e9 : <source_computer> peut d\u00e9l\u00e9guer vers <target_server>'"}]},
        ]
    ),
    "users_constrained_delegations": (
        "Constrained Delegation Users",
        "Users configured with constrained Kerberos delegation.",
        "Kerberos",
        [
            {"step": 1, "priority": "normal", "icon": "bi-search", "title": "Review constrained delegation assignments",
             "detail": "List all users with constrained delegation configured and verify each is legitimate.",
             "commands": [{"label": "PowerShell", "code": "Get-ADUser -Filter {msDS-AllowedToDelegateTo -ne '$null'} -Properties msDS-AllowedToDelegateTo | Select-Object Name, SamAccountName, msDS-AllowedToDelegateTo"}]},
            {"step": 2, "priority": "normal", "icon": "bi-diagram-2", "title": "Migrer vers la d\u00e9l\u00e9gation bas\u00e9e sur les ressources (RBCD)",
             "detail": "La RBCD est plus s\u00fbre car c'est le service cible qui contr\u00f4le quels comptes peuvent d\u00e9l\u00e9guer vers lui (attribut msDS-AllowedToActOnBehalfOfOtherIdentity). Supprimer la d\u00e9l\u00e9gation contrainte sur la source et configurer RBCD sur la cible.",
             "commands": [{"label": "PowerShell \u2014 supprimer KCD source et configurer RBCD sur la cible", "code": "# 1. Supprimer la d\u00e9l\u00e9gation contrainte existante sur le compte source :\nSet-ADUser <source_user> -Clear msDS-AllowedToDelegateTo\nSet-ADAccountControl <source_user> -TrustedToAuthForDelegation $false\n\n# 2. Configurer RBCD sur le serveur cible :\n$sourceSid = (Get-ADUser <source_user>).SID\n$sd = New-Object Security.AccessControl.RawSecurityDescriptor \"O:BAD:(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;$($sourceSid.Value))\"\n$sdb = New-Object byte[] ($sd.BinaryLength)\n$sd.GetBinaryForm($sdb, 0)\nGet-ADComputer <target_server> | Set-ADObject -Replace @{'msDS-AllowedToActOnBehalfOfOtherIdentity' = $sdb}\nWrite-Host 'RBCD : <source_user> peut maintenant d\u00e9l\u00e9guer vers <target_server>'\n\n# V\u00e9rifier :\n$raw = (Get-ADComputer <target_server> -Properties msDS-AllowedToActOnBehalfOfOtherIdentity).'msDS-AllowedToActOnBehalfOfOtherIdentity'\nif ($raw) { (New-Object Security.AccessControl.RawSecurityDescriptor($raw,0)).DiscretionaryAcl | Select-Object * }"}]},
        ]
    ),
    "has_sid_history": (
        "SID History Present",
        "Accounts with SID history that could be used for privilege escalation.",
        "Misc",
        [
            {"step": 1, "priority": "normal", "icon": "bi-search", "title": "Enumerate accounts with SID history",
             "detail": "SID History is used during domain migrations. After migration is complete, it should be removed.",
             "commands": [{"label": "PowerShell", "code": "Get-ADUser -Filter {SIDHistory -ne '$null'} -Properties SIDHistory | Select-Object Name, SamAccountName, SIDHistory"}]},
            {"step": 2, "priority": "normal", "icon": "bi-trash3", "title": "Clear SID History after domain migration",
             "detail": "Once domain migration is validated, remove SID History from accounts to eliminate the potential escalation path.",
             "commands": [{"label": "PowerShell", "code": "# Requires domain migration tools or specific permissions\nGet-ADUser -Filter {SIDHistory -ne '$null'} | Set-ADUser -Remove @{SIDHistory = (Get-ADUser <user> -Properties SIDHistory).SIDHistory}"}]},
        ]
    ),
    "vuln_permissions_adminsdholder": (
        "AdminSDHolder Permission Anomalies",
        "Unexpected permissions on the AdminSDHolder container.",
        "Permissions",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Audit AdminSDHolder ACL",
             "detail": "The AdminSDHolder object's ACL is propagated to all protected accounts every 60 min by SDProp. Any unauthorized ACE here is critical.",
             "commands": [{"label": "PowerShell", "code": "$asdh = 'CN=AdminSDHolder,CN=System,DC=domain,DC=com'\n(Get-Acl \"AD:$asdh\").Access | Where-Object {\n    $_.AccessControlType -eq 'Allow' -and\n    $_.ActiveDirectoryRights -match 'GenericAll|WriteDacl|WriteOwner'\n} | Select-Object IdentityReference, ActiveDirectoryRights"}]},
            {"step": 2, "priority": "high", "icon": "bi-trash3", "title": "Remove unauthorized ACEs from AdminSDHolder",
             "detail": "Remove any ACE that is not from Domain Admins, Enterprise Admins, or SYSTEM. These ACEs will propagate to ALL protected accounts.",
             "commands": [{"label": "PowerShell", "code": "$dn = 'CN=AdminSDHolder,CN=System,DC=domain,DC=com'\n$acl = Get-Acl \"AD:$dn\"\n$ace = $acl.Access | Where-Object {$_.IdentityReference -eq 'DOMAIN\\baduser'}\n$acl.RemoveAccessRule($ace)\nSet-Acl \"AD:$dn\" $acl"}]},
        ]
    ),
    "vuln_functional_level": (
        "Outdated Domain Functional Level",
        "Domain or forest functional level is below the current recommended standard.",
        "Misc",
        [
            {"step": 1, "priority": "normal", "icon": "bi-info-circle", "title": "Check current functional levels",
             "detail": "Identify the current domain and forest functional levels.",
             "commands": [{"label": "PowerShell", "code": "(Get-ADDomain).DomainMode\n(Get-ADForest).ForestMode"}]},
            {"step": 2, "priority": "normal", "icon": "bi-arrow-up-circle", "title": "Plan functional level upgrade",
             "detail": "Before raising, ensure all DCs run an OS version compatible with the target functional level, and no legacy applications require the old level.",
             "commands": [{"label": "PowerShell — raise domain FL", "code": "Set-ADDomainMode -Identity 'domain.com' -DomainMode Windows2016Domain"}]},
        ]
    ),
    "computers_os_obsolete": (
        "Obsolete Operating Systems",
        "Computers running end-of-life operating systems.",
        "Misc",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Inventory obsolete OS versions",
             "detail": "Identify all machines running end-of-life systems (Windows 7, Server 2008, XP, etc.).",
             "commands": [{"label": "PowerShell", "code": "Get-ADComputer -Filter {Enabled -eq $true} -Properties OperatingSystem | Where-Object {\n    $_.OperatingSystem -match '2003|2008|XP|Vista|Windows 7|Windows 8|2012'\n} | Select-Object Name, OperatingSystem | Sort-Object OperatingSystem"}]},
            {"step": 2, "priority": "high", "icon": "bi-box-arrow-up", "title": "Upgrade or isolate end-of-life systems",
             "detail": "Upgrade to a supported OS. If upgrade is not possible, isolate the machine in a dedicated VLAN with strict firewall rules.",
             "commands": []},
            {"step": 3, "priority": "normal", "icon": "bi-shield-slash", "title": "Isoler les syst\u00e8mes EOL par micro-segmentation",
             "detail": "Placer les machines EOL dans un VLAN de quarantaine avec des r\u00e8gles strictes. Bloquer SMB (445), RPC (135), WinRM (5985/5986) en inbound depuis les segments non approuv\u00e9s. N'autoriser que les flux strictement n\u00e9cessaires.",
             "commands": [{"label": "PowerShell \u2014 r\u00e8gles de pare-feu Windows sur la machine EOL", "code": "# Bloquer SMB entrant sauf depuis les DCs :\nNew-NetFirewallRule -DisplayName 'Block Inbound SMB (non-DC)' -Direction Inbound -Protocol TCP -LocalPort 445 -Action Block -Profile Domain\n\n# Bloquer RPC :\nNew-NetFirewallRule -DisplayName 'Block Inbound RPC' -Direction Inbound -Protocol TCP -LocalPort 135 -Action Block -Profile Domain\n\n# Bloquer WinRM :\nNew-NetFirewallRule -DisplayName 'Block Inbound WinRM' -Direction Inbound -Protocol TCP -LocalPort 5985,5986 -Action Block -Profile Domain\n\n# V\u00e9rifier les r\u00e8gles actives :\nGet-NetFirewallRule | Where-Object { $_.Enabled -eq 'True' -and $_.Direction -eq 'Inbound' } | Select-Object DisplayName, Action, LocalPort"}]},
        ]
    ),
    "can_read_laps": (
        "Unauthorized LAPS Password Readers",
        "Non-admin accounts that can read LAPS passwords.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "normal", "icon": "bi-search", "title": "Audit LAPS read permissions",
             "detail": "Find all accounts with the ability to read the ms-Mcs-AdmPwd or msLAPS-Password attributes.",
             "commands": [{"label": "PowerShell (LAPS v1)", "code": "# Requires LAPS PowerShell module\nFind-AdmPwdExtendedRights -Identity 'OU=Workstations,DC=domain,DC=com'"}]},
            {"step": 2, "priority": "normal", "icon": "bi-x-circle", "title": "Remove unauthorized read access",
             "detail": "Remove LAPS read permissions from any account that does not strictly require it.",
             "commands": [{"label": "PowerShell (LAPS v1)", "code": "Set-AdmPwdReadPasswordPermission -OrgUnit 'OU=Workstations,DC=domain,DC=com' -AllowedPrincipals '<approved_group>'"}]},
        ]
    ),
    "users_rdp_access": (
        "Excessive RDP Access",
        "Users with RDP access to systems they should not have access to.",
        "Network",
        [
            {"step": 1, "priority": "normal", "icon": "bi-search", "title": "Audit Remote Desktop Users group membership",
             "detail": "Review the Remote Desktop Users local group on all servers and workstations.",
             "commands": [{"label": "PowerShell", "code": "Invoke-Command -ComputerName <server> { net localgroup 'Remote Desktop Users' }"}]},
            {"step": 2, "priority": "normal", "icon": "bi-person-dash", "title": "Remove unauthorized RDP access",
             "detail": "Only users who explicitly need RDP access should be in this group. Remove all others.",
             "commands": []},
            {"step": 3, "priority": "normal", "icon": "bi-shield-lock", "title": "Restrict RDP via GPO and NLA",
             "detail": "Enforce Network Level Authentication (NLA) for RDP and restrict RDP access via GPO to specific groups only.",
             "commands": [{"label": "GPO", "code": "Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Security\n'Require user authentication for remote connections by using NLA' = Enabled"}]},
        ]
    ),
    "unpriv_to_dnsadmins": (
        "Path to DNSAdmins",
        "Unprivileged accounts with a path to the DNSAdmins group.",
        "Attack Paths",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Audit DNSAdmins group membership",
             "detail": "DNSAdmins members can execute code on DCs by loading a malicious DLL via DNS Server. Review membership strictly.",
             "commands": [{"label": "PowerShell", "code": "Get-ADGroupMember -Identity 'DnsAdmins' -Recursive | Select-Object Name, SamAccountName, objectClass"}]},
            {"step": 2, "priority": "high", "icon": "bi-person-dash", "title": "Remove unnecessary members from DNSAdmins",
             "detail": "This group should have minimal members (ideally only dedicated DNS admin accounts, not service desk staff).",
             "commands": [{"label": "PowerShell", "code": "Remove-ADGroupMember -Identity 'DnsAdmins' -Members 'DOMAIN\\user' -Confirm:$false"}]},
            {"step": 3, "priority": "normal", "icon": "bi-scissors", "title": "Break attack paths to DNSAdmins",
             "detail": "Remove ACEs or group memberships that allow unprivileged accounts to reach DNSAdmins.",
             "commands": []},
        ]
    ),
    "dom_admin_on_non_dc": (
        "Domain Admins Logged On Non-DC",
        "Domain admin sessions detected on non-domain-controller machines.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "high", "icon": "bi-exclamation-triangle", "title": "Identify DA accounts used on non-DC systems",
             "detail": "Credential exposure on workstations/servers is a major risk — credentials can be extracted with tools like Mimikatz.",
             "commands": [{"label": "PowerShell — check recent logons", "code": "Get-WinEvent -ComputerName <server> -FilterHashtable @{LogName='Security'; Id=4624} | Where-Object {$_.Message -match 'Domain Admins'}"}]},
            {"step": 2, "priority": "high", "icon": "bi-diagram-3", "title": "Appliquer le Tiering AD \u2014 interdire les connexions DA hors Tier 0",
             "detail": "Les comptes Domain Admin ne doivent se connecter QUE sur des DCs. Cr\u00e9er une GPO li\u00e9e aux OUs Servers (Tier 1) ET Workstations (Tier 2) qui interdit explicitement la connexion des DA/EA via les User Rights Assignment.",
             "commands": [{"label": "GPO \u2014 User Rights Assignment sur OUs Tier 1 & 2", "code": "# Computer Configuration > Policies > Windows Settings > Security Settings >\n#   Local Policies > User Rights Assignment\n#\n# Ajouter Domain Admins, Enterprise Admins, Schema Admins dans :\n#   Deny log on locally                   (SeInteractiveLogonRight)\n#   Deny log on through Remote Desktop    (SeRemoteInteractiveLogonRight)\n#   Deny log on as a batch job            (SeBatchLogonRight)\n#   Deny log on as a service             (SeServiceLogonRight)\n\n# V\u00e9rifier la politique effective sur un serveur cible :\nInvoke-Command -ComputerName <server> {\n    secedit /export /cfg C:\\Temp\\secpol.cfg /areas USER_RIGHTS\n    Get-Content C:\\Temp\\secpol.cfg | Select-String 'SeDenyInteractive|SeDenyRemote|SeDenyBatch|SeDenyService'\n}"}]},
            {"step": 3, "priority": "normal", "icon": "bi-pc-display-horizontal", "title": "D\u00e9ployer des Privileged Access Workstations (PAW)",
             "detail": "Durcir un poste d\u00e9di\u00e9 exclusivement \u00e0 l'administration Tier 0. Activer Credential Guard, bloquer l'acc\u00e8s internet, AppLocker/WDAC pour ex\u00e9cutables autoris\u00e9s uniquement.",
             "commands": [{"label": "PowerShell \u2014 activer Credential Guard (VBS)", "code": "# Activer Virtualization-Based Security + Credential Guard sur la PAW :\n$basePath = 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard'\nSet-ItemProperty $basePath -Name 'EnableVirtualizationBasedSecurity'   -Value 1 -Type DWord\nSet-ItemProperty $basePath -Name 'RequirePlatformSecurityFeatures'     -Value 3 -Type DWord  # Secure Boot + DMA\nSet-ItemProperty $basePath -Name 'HypervisorEnforcedCodeIntegrity'     -Value 1 -Type DWord\n$cgPath = 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa'\nSet-ItemProperty $cgPath   -Name 'LsaCfgFlags'                         -Value 1 -Type DWord  # Credential Guard enabled\n# V\u00e9rifier apr\u00e8s red\u00e9marrage :\nGet-ComputerInfo | Select-Object DeviceGuard*"}]},
        ]
    ),
    "users_pwd_cleartext": (
        "Passwords in Cleartext",
        "Accounts storing or transmitting passwords in cleartext.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "critical", "icon": "bi-search", "title": "Identify Reversible Encryption accounts",
             "detail": "Find accounts with 'Store password using reversible encryption' enabled.",
             "commands": [{"label": "PowerShell", "code": "Get-ADUser -Filter {AllowReversiblePasswordEncryption -eq $true} -Properties AllowReversiblePasswordEncryption | Select-Object Name, SamAccountName"}]},
            {"step": 2, "priority": "critical", "icon": "bi-toggle-off", "title": "Disable reversible encryption and force password reset",
             "detail": "Disable the reversible encryption flag and immediately force a password reset for affected accounts.",
             "commands": [{"label": "PowerShell", "code": "Get-ADUser -Filter {AllowReversiblePasswordEncryption -eq $true} | Set-ADUser -AllowReversiblePasswordEncryption $false\n# Force password reset:\nSet-ADUser <user> -ChangePasswordAtLogon $true"}]},
        ]
    ),
    "guest_accounts": (
        "Active Guest Accounts",
        "Guest accounts that are enabled.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "normal", "icon": "bi-person-x", "title": "Disable all guest accounts",
             "detail": "Guest accounts should be disabled on all systems. They provide unauthenticated access and are a common attack vector.",
             "commands": [{"label": "PowerShell — domain guest", "code": "Disable-ADAccount -Identity 'Guest'\n# Also check local guest accounts on all machines via GPO:\n# Computer Config > Windows Settings > Security Settings > Local Policies > Security Options\n# 'Accounts: Guest account status' = Disabled"}]},
        ]
    ),
    "users_password_not_required": (
        "Accounts Without Password Requirement",
        "Accounts where a password is not required to log in.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Enumerate accounts with PASSWD_NOTREQD flag",
             "detail": "Find accounts where the PASSWD_NOTREQD flag is set (UAC flag 0x0020).",
             "commands": [{"label": "PowerShell", "code": "Get-ADUser -Filter {PasswordNotRequired -eq $true -and Enabled -eq $true} -Properties PasswordNotRequired | Select-Object Name, SamAccountName"}]},
            {"step": 2, "priority": "high", "icon": "bi-key-fill", "title": "Set strong passwords and remove the flag",
             "detail": "Set a strong password and clear the PASSWD_NOTREQD flag. If it is a service account, migrate to gMSA.",
             "commands": [{"label": "PowerShell", "code": "Set-ADUser <user> -PasswordNotRequired $false\n# Set a new strong temporary password:\nSet-ADAccountPassword <user> -Reset -NewPassword (ConvertTo-SecureString 'NewP@ssw0rd!' -AsPlainText -Force)"}]},
        ]
    ),
    "objects_to_adcs": (
        "Paths to ADCS",
        "Objects with paths to Active Directory Certificate Services.",
        "Attack Paths",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Audit ADCS permissions and templates",
             "detail": "Review Enrollment Agent templates, vulnerable template configurations (ESC1-ESC8), and CA permissions.",
             "commands": [{"label": "Certify (from attacker perspective)", "code": "# Use Certipy or Certify to enumerate vulnerable templates:\n# certify.exe find /vulnerable\n# certipy find -u user@domain.com -p password -dc-ip <dc_ip>"}]},
            {"step": 2, "priority": "high", "icon": "bi-shield-lock", "title": "Durcir les templates ADCS vuln\u00e9rables (ESC1 \u2013 ESC4)",
             "detail": "ESC1 : supprimer CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT des templates. ESC2 : retirer 'Any Purpose' / 'Client Authentication' des templates \u00e0 enr\u00f4lement faible. ESC3 : retirer les droits Enrollment Agent des non-admins CA. ESC4 : retirer les permissions Write sur les objets template.",
             "commands": [{"label": "PowerShell \u2014 identifier et corriger ESC1 (Enrollee Supplies Subject)", "code": "# Identifier les templates vuln\u00e9rables ESC1 :\n$tmplBase = 'CN=Certificate Templates,CN=Public Key Services,CN=Services,CN=Configuration,DC=domain,DC=com'\n$vuln = Get-ADObject -SearchBase $tmplBase -Filter {objectClass -eq 'pKICertificateTemplate'} -Properties msPKI-Certificate-Name-Flag, msPKI-RA-Signature, 'msPKI-Enrollment-Flag' |\n    Where-Object { ($_.'msPKI-Certificate-Name-Flag' -band 1) -and ($_.'msPKI-RA-Signature' -eq 0) }\n$vuln | Select-Object Name, 'msPKI-Certificate-Name-Flag'\n\n# Corriger ESC1 : supprimer le flag CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT (bit 0)\nforeach ($t in $vuln) {\n    $newFlag = $t.'msPKI-Certificate-Name-Flag' -band (-bnot 1)\n    Set-ADObject $t.DistinguishedName -Replace @{'msPKI-Certificate-Name-Flag' = $newFlag}\n    Write-Host \"Corrig\u00e9 : $($t.Name)\"\n}"}, {"label": "Certipy \u2014 \u00e9num\u00e9rer tous les chemins ESC (Linux/Windows)", "code": "# Depuis Linux :\ncertipy find -u admin@domain.com -p 'Password' -dc-ip <DC_IP> -vulnerable -stdout\n\n# Depuis Windows :\nCertify.exe find /vulnerable"}]},
            {"step": 3, "priority": "normal", "icon": "bi-graph-up", "title": "Durcir le Web Enrollment CA \u2014 HTTPS + EPA, pas de NTLM (ESC8)",
             "detail": "Le endpoint HTTP du CA Web Enrollment est vuln\u00e9rable au relay NTLM (ESC8/PetitPotam). Imposer HTTPS, activer EPA (Extended Protection for Authentication) et d\u00e9sactiver NTLM sur ce endpoint IIS.",
             "commands": [{"label": "PowerShell \u2014 activer EPA et HTTPS sur IIS CertSrv", "code": "# Ex\u00e9cuter sur le serveur CA\nImport-Module WebAdministration\n\n# Exiger SSL sur CertSrv\nSet-WebConfigurationProperty -Filter 'system.webServer/security/access' `\n    -Name 'sslFlags' -Value 'Ssl' `\n    -PSPath 'IIS:\\Sites\\Default Web Site\\CertSrv'\n\n# Activer Extended Protection (EPA) :\nSet-WebConfigurationProperty `\n    -Filter 'system.webServer/security/authentication/windowsAuthentication' `\n    -Name 'extendedProtection.tokenChecking' `\n    -Value 'Require' `\n    -PSPath 'IIS:\\Sites\\Default Web Site\\CertSrv'\n\n# V\u00e9rifier :\nGet-WebConfigurationProperty -Filter 'system.webServer/security/authentication/windowsAuthentication' `\n    -Name 'extendedProtection.tokenChecking' `\n    -PSPath 'IIS:\\Sites\\Default Web Site\\CertSrv'"}]},
        ]
    ),
    "cross_domain_admin_privileges": (
        "Cross-Domain Admin Privileges",
        "Accounts with administrative privileges spanning multiple domains.",
        "Permissions",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Auditer les appartenances admin inter-domaines",
             "detail": "Trouver les comptes d'un domaine membres de groupes privil\u00e9gi\u00e9s dans d'autres domaines. Les Foreign Security Principals dans des groupes Tier 0 sont un vecteur d'escalade inter-domaines courant.",
             "commands": [{"label": "PowerShell \u2014 Foreign Security Principals dans groupes privil\u00e9gi\u00e9s", "code": "$privilegedGroups = @('Domain Admins','Enterprise Admins','Schema Admins','Administrators','Backup Operators','Account Operators')\nforeach ($grp in $privilegedGroups) {\n    try {\n        $members = Get-ADGroupMember -Identity $grp -ErrorAction Stop\n        $foreign = $members | Where-Object { $_.objectClass -eq 'foreignSecurityPrincipal' }\n        if ($foreign) {\n            Write-Host \"[!] Membres \u00e9trangers dans $grp :\"\n            $foreign | ForEach-Object {\n                $fsp = Get-ADObject -Identity $_.DistinguishedName -Properties objectSid\n                Write-Host \"  - $($fsp.Name)  SID: $($fsp.objectSid)\"\n            }\n        }\n    } catch {}\n}"}]},
            {"step": 2, "priority": "high", "icon": "bi-x-circle", "title": "Remove unnecessary cross-domain privileges",
             "detail": "Cross-domain admin rights should be extremely limited. Use trusts with SID filtering to prevent privilege escalation across domains.",
             "commands": [{"label": "PowerShell — enable SID filtering on trust", "code": "netdom trust <TrustingDomain> /domain:<TrustedDomain> /quarantine:yes"}]},
        ]
    ),
    "users_shadow_credentials": (
        "Shadow Credentials on Users",
        "Users with shadow credentials set, allowing impersonation.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "critical", "icon": "bi-search", "title": "List users with msDS-KeyCredentialLink set",
             "detail": "Shadow credentials allow an attacker to obtain a TGT for the account without knowing its password.",
             "commands": [{"label": "PowerShell", "code": "Get-ADUser -Filter * -Properties msDS-KeyCredentialLink | Where-Object {$_.'msDS-KeyCredentialLink'} | Select-Object Name, SamAccountName, 'msDS-KeyCredentialLink'"}]},
            {"step": 2, "priority": "critical", "icon": "bi-trash3", "title": "Clear unauthorized shadow credentials",
             "detail": "Remove the msDS-KeyCredentialLink attribute from all accounts where it was not explicitly configured by a legitimate MFA/WHfB solution.",
             "commands": [{"label": "PowerShell", "code": "Set-ADUser -Identity <user> -Clear msDS-KeyCredentialLink"}]},
        ]
    ),
    "users_shadow_credentials_to_non_admins": (
        "Shadow Credentials Targeting Non-Admins",
        "Shadow credentials set on non-privileged accounts.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Inventorier les utilisateurs avec msDS-KeyCredentialLink d\u00e9fini",
             "detail": "Les Shadow Credentials sur n'importe quel compte permettent d'obtenir un TGT sans conna\u00eetre le mot de passe. M\u00eame sur un compte non-admin, c'est un maillon exploitable dans une cha\u00eene d'escalade.",
             "commands": [{"label": "PowerShell \u2014 lister les comptes affect\u00e9s avec date de modification", "code": "Get-ADUser -Filter * -Properties msDS-KeyCredentialLink, whenChanged |\n    Where-Object { $_.'msDS-KeyCredentialLink' } |\n    Select-Object Name, SamAccountName, whenChanged, @{N='KeyCount';E={$_.'msDS-KeyCredentialLink'.Count}} |\n    Sort-Object whenChanged -Descending"}]},
            {"step": 2, "priority": "high", "icon": "bi-trash3", "title": "Supprimer les Shadow Credentials non autoris\u00e9es",
             "detail": "Retirer msDS-KeyCredentialLink de tous les comptes o\u00f9 cet attribut n'a pas \u00e9t\u00e9 positionn\u00e9 par un d\u00e9ploiement l\u00e9gitime (Windows Hello for Business, Azure AD Hybrid Join).",
             "commands": [{"label": "PowerShell \u2014 nettoyage en masse", "code": "Get-ADUser -Filter * -Properties msDS-KeyCredentialLink | Where-Object { $_.'msDS-KeyCredentialLink' } | ForEach-Object {\n    Write-Host \"Nettoyage Shadow Credentials : $($_.SamAccountName)\"\n    Set-ADUser -Identity $_.DistinguishedName -Clear msDS-KeyCredentialLink\n}"}]},
            {"step": 3, "priority": "normal", "icon": "bi-bell", "title": "Surveiller les \u00e9critures sur msDS-KeyCredentialLink via SACL",
             "detail": "Ajouter une SACL sur le container Users pour auditer toute \u00e9criture de l'attribut msDS-KeyCredentialLink. Alerter sur l'Event ID 5136 (Directory Service object modified) pour cet attribut OID.",
             "commands": [{"label": "PowerShell \u2014 activer l'audit DS et la SACL", "code": "# 1. Activer 'Audit Directory Service Changes' via GPO :\n#    Computer Config > Policies > Windows Settings > Security Settings >\n#    Advanced Audit Policy > DS Access > Audit Directory Service Changes = Success\n\n# 2. Ajouter une SACL sur le container Users :\n$acl = Get-Acl 'AD:CN=Users,DC=domain,DC=com'\n$everyone = [System.Security.Principal.SecurityIdentifier]::new('S-1-1-0')\n# OID de msDS-KeyCredentialLink : 5b47d60f-6090-40b2-9f37-2a4de88f3063\n$attrGuid  = [guid]'5b47d60f-6090-40b2-9f37-2a4de88f3063'\n$userClass = [guid]'bf967aba-0de6-11d0-a285-00aa003049e2'\n$auditRule = New-Object System.DirectoryServices.ActiveDirectoryAuditRule(\n    $everyone, 'WriteProperty', 'Success', $attrGuid, 'Descendents', $userClass\n)\n$acl.AddAuditRule($auditRule)\nSet-Acl 'AD:CN=Users,DC=domain,DC=com' $acl\nWrite-Host 'SACL configur\u00e9e sur CN=Users'"}]},
        ]
    ),
    "can_read_gmsapassword_of_adm": (
        "Unauthorized gMSA Password Readers",
        "Accounts that can read the gMSA password of privileged accounts.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Audit gMSA PrincipalsAllowedToRetrieveManagedPassword",
             "detail": "Find gMSA accounts where unauthorized principals can retrieve the managed password.",
             "commands": [{"label": "PowerShell", "code": "Get-ADServiceAccount -Filter * -Properties PrincipalsAllowedToRetrieveManagedPassword | Select-Object Name, PrincipalsAllowedToRetrieveManagedPassword"}]},
            {"step": 2, "priority": "high", "icon": "bi-x-circle", "title": "Restrict gMSA password retrieval",
             "detail": "Only the server(s) that need to use the gMSA should be in PrincipalsAllowedToRetrieveManagedPassword.",
             "commands": [{"label": "PowerShell", "code": "Set-ADServiceAccount -Identity <gMSA> -PrincipalsAllowedToRetrieveManagedPassword @('<server1>$', '<server2>$')"}]},
        ]
    ),
    "users_GPO_access": (
        "Excessive GPO Write Access",
        "Users with write access to Group Policy Objects.",
        "Permissions",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Audit GPO modify permissions",
             "detail": "List all non-admin accounts with GPO edit rights.",
             "commands": [{"label": "PowerShell", "code": "Get-GPO -All | ForEach-Object {\n    $perm = Get-GPPermission -Guid $_.Id -All\n    $perm | Where-Object {$_.Permission -eq 'GpoEdit' -or $_.Permission -eq 'GpoEditDeleteModifySecurity'} | Select-Object @{N='GPO';E={$_.DisplayName}}, Trustee, Permission\n}"}]},
            {"step": 2, "priority": "high", "icon": "bi-x-circle", "title": "Remove unauthorized GPO write permissions",
             "detail": "Only designated Group Policy administrators should have edit rights on GPOs.",
             "commands": [{"label": "PowerShell", "code": "Set-GPPermission -Guid <GPO_ID> -TargetName 'DOMAIN\\user' -TargetType User -PermissionLevel None"}]},
        ]
    ),
    "computers_members_high_privilege": (
        "Computers in High-Privilege Groups",
        "Computer accounts that are members of high-privilege groups.",
        "Permissions",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Identify computer accounts in privileged groups",
             "detail": "Computer accounts in Domain Admins, Enterprise Admins, or similar groups are extreme privilege escalation risks.",
             "commands": [{"label": "PowerShell", "code": "@('Domain Admins','Enterprise Admins','Schema Admins') | ForEach-Object {\n    Get-ADGroupMember $_ -Recursive | Where-Object {$_.objectClass -eq 'computer'} | Select-Object @{N='Group';E={$_}}, Name\n}"}]},
            {"step": 2, "priority": "high", "icon": "bi-person-dash", "title": "Remove computer accounts from privileged groups",
             "detail": "Computer accounts should never be in privileged groups.",
             "commands": [{"label": "PowerShell", "code": "Remove-ADGroupMember -Identity 'Domain Admins' -Members '<computer>$' -Confirm:$false"}]},
        ]
    ),
    "graph_list_objects_rbcd": (
        "Resource-Based Constrained Delegation (RBCD)",
        "Objects configured with RBCD that could allow privilege escalation.",
        "Kerberos",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Enumerate RBCD configurations",
             "detail": "Find all objects with msDS-AllowedToActOnBehalfOfOtherIdentity set.",
             "commands": [{"label": "PowerShell", "code": "Get-ADComputer -Filter * -Properties msDS-AllowedToActOnBehalfOfOtherIdentity | Where-Object {$_.'msDS-AllowedToActOnBehalfOfOtherIdentity'} | Select-Object Name"}]},
            {"step": 2, "priority": "high", "icon": "bi-x-circle", "title": "Remove unauthorized RBCD entries",
             "detail": "Clear RBCD configurations that were not explicitly and legitimately set.",
             "commands": [{"label": "PowerShell", "code": "Set-ADComputer -Identity <computer> -Clear msDS-AllowedToActOnBehalfOfOtherIdentity"}]},
        ]
    ),
    "computer_admin_of_computers": (
        "Computer Accounts Admin of Computers",
        "Computer accounts with admin rights on other computers.",
        "Permissions",
        [
            {"step": 1, "priority": "high", "icon": "bi-search", "title": "Identify computer-to-computer admin paths",
             "detail": "A compromised machine can leverage this to move laterally to other systems.",
             "commands": []},
            {"step": 2, "priority": "high", "icon": "bi-x-circle", "title": "Remove computer accounts from local admin groups",
             "detail": "Computer accounts should not be members of local Administrators on other computers.",
             "commands": [{"label": "PowerShell", "code": "Invoke-Command -ComputerName <target> {\n    Remove-LocalGroupMember -Group 'Administrators' -Member '<source_computer>$'\n}"}]},
        ]
    ),
    "da_to_da": (
        "DA-to-DA Trust Paths",
        "Paths between Domain Admin accounts across domains.",
        "Attack Paths",
        [
            {"step": 1, "priority": "high", "icon": "bi-shield-fill-exclamation", "title": "Enable SID filtering on forest trusts",
             "detail": "SID filtering (quarantine) prevents SID history abuse across domain trusts.",
             "commands": [{"label": "Command", "code": "netdom trust <TrustingDomain> /domain:<TrustedDomain> /quarantine:yes /enablesidhistory:no"}]},
            {"step": 2, "priority": "normal", "icon": "bi-diagram-3", "title": "Isoler les comptes admin Tier 0 par domaine",
             "detail": "Chaque domaine doit avoir ses propres comptes admin d\u00e9di\u00e9s. Supprimer les appartenances crois\u00e9es entre domaines. V\u00e9rifier qu'aucun Foreign Security Principal n'est dans des groupes privil\u00e9gi\u00e9s.",
             "commands": [{"label": "PowerShell \u2014 Foreign Security Principals dans les groupes Tier 0", "code": "@('Domain Admins','Enterprise Admins','Schema Admins','Administrators') | ForEach-Object {\n    $grp = $_\n    try {\n        Get-ADGroupMember $grp | Where-Object { $_.objectClass -eq 'foreignSecurityPrincipal' } |\n        ForEach-Object {\n            $fsp = Get-ADObject -Identity $_.DistinguishedName -Properties objectSid -ErrorAction SilentlyContinue\n            [pscustomobject]@{\n                Group = $grp\n                FSP   = $fsp.Name\n                SID   = $fsp.objectSid\n                DN    = $fsp.DistinguishedName\n            }\n        }\n    } catch {}\n}\n\n# Supprimer un FSP d'un groupe privil\u00e9gi\u00e9 :\n# Remove-ADGroupMember -Identity 'Domain Admins' -Members 'CN=S-1-5-21-...,CN=ForeignSecurityPrincipals,...' -Confirm:$false"}]},
        ]
    ),
    "krb_last_change": (
        "Stale KRBTGT Password",
        "KRBTGT account password not changed in over 180 days.",
        "Kerberos",
        [
            {"step": 1, "priority": "high", "icon": "bi-key-fill", "title": "Reset KRBTGT password (twice, 10+ hours apart)",
             "detail": "The KRBTGT password must be reset TWICE to invalidate all existing Golden Tickets. Wait at least 10 hours between resets to allow replication.",
             "commands": [{"label": "PowerShell", "code": "# Use Microsoft's New-KrbtgtKeys.ps1 script (safer than manual reset)\n# https://github.com/microsoft/New-KrbtgtKeys.ps1\n. .\\New-KrbtgtKeys.ps1\nInvoke-KrbtgtReset -Domain 'domain.com' -DomainController '<PDC>' -Scope AllDCs"}]},
            {"step": 2, "priority": "normal", "icon": "bi-calendar2-check", "title": "Schedule regular KRBTGT rotation",
             "detail": "Rotate the KRBTGT password at least every 180 days as recommended by Microsoft.",
             "commands": []},
        ]
    ),
    "fgpp": (
        "Fine-Grained Password Policies",
        "Fine-grained password policies configured in the domain.",
        "Credentials / Authentication",
        [
            {"step": 1, "priority": "normal", "icon": "bi-search", "title": "Review existing Fine-Grained Password Policies",
             "detail": "List all PSOs (Password Settings Objects) and verify they enforce adequate complexity and length.",
             "commands": [{"label": "PowerShell", "code": "Get-ADFineGrainedPasswordPolicy -Filter * | Select-Object Name, Precedence, MinPasswordLength, PasswordHistoryCount, MaxPasswordAge, LockoutThreshold"}]},
            {"step": 2, "priority": "normal", "icon": "bi-shield-plus", "title": "Apply FGPP to privileged accounts",
             "detail": "Apply stricter password policies (25+ chars for service accounts, 20+ for admins) using PSOs targeting specific groups.",
             "commands": [{"label": "PowerShell", "code": "New-ADFineGrainedPasswordPolicy -Name 'PSO-Admins' -Precedence 10 -MinPasswordLength 20 -PasswordHistoryCount 24 -MaxPasswordAge '90.00:00:00' -ComplexityEnabled $true -ReversibleEncryptionEnabled $false\nAdd-ADFineGrainedPasswordPolicySubject 'PSO-Admins' -Subjects 'Domain Admins'"}]},
        ]
    ),
    "nb_domain_admins": (
        "Number of Domain Admins",
        "Total count of Domain Admin accounts.",
        "Misc",
        [
            {"step": 1, "priority": "normal", "icon": "bi-people", "title": "Review and reduce Domain Admin membership",
             "detail": "Best practice: fewer than 5 Domain Admin accounts. Ideally, only dedicated 'break-glass' accounts.",
             "commands": [{"label": "PowerShell", "code": "Get-ADGroupMember -Identity 'Domain Admins' -Recursive | Select-Object Name, SamAccountName, objectClass"}]},
            {"step": 2, "priority": "normal", "icon": "bi-clock-history", "title": "Impl\u00e9menter l'acc\u00e8s privil\u00e9gi\u00e9 Just-In-Time (JIT)",
             "detail": "Utiliser Microsoft PIM (Entra ID P2) ou implanter du JIT on-premises avec appartenance temporaire et expiration automatique. Les droits DA ne doivent \u00eatre accord\u00e9s que sur demande approuv\u00e9e avec dur\u00e9e limit\u00e9e.",
             "commands": [{"label": "PowerShell \u2014 JIT on-premises (appartenance temporaire \u00e0 dur\u00e9e limit\u00e9e)", "code": "# Fonction d'acc\u00e8s DA temporaire (2h par d\u00e9faut) :\nfunction Grant-TempDA {\n    param([string]$User, [int]$Hours = 2)\n    Add-ADGroupMember -Identity 'Domain Admins' -Members $User\n    $expiry = (Get-Date).AddHours($Hours).ToString('HH:mm')\n    Write-EventLog -LogName Application -Source 'JIT-Admin' -EventId 1000 -EntryType Information `\n        -Message \"JIT DA granted to $User for $Hours hours (expires $expiry)\"\n    Start-Job -Name \"Revoke-DA-$User\" -ScriptBlock {\n        param($u, $h)\n        Start-Sleep -Seconds ($h * 3600)\n        Remove-ADGroupMember -Identity 'Domain Admins' -Members $u -Confirm:$false\n        Write-EventLog -LogName Application -Source 'JIT-Admin' -EventId 1001 -EntryType Information `\n            -Message \"JIT DA revoked for $u (TTL expired)\"\n    } -ArgumentList $User, $Hours | Out-Null\n    Write-Host \"[JIT] $User ajout\u00e9 \u00e0 Domain Admins pour $Hours heure(s). Expiration : $expiry\"\n}\n# Exemple : Grant-TempDA -User 'john.doe' -Hours 2"}]},
        ]
    ),
    "empty_groups": (
        "Empty Groups",
        "Security groups with no members (may indicate orphaned groups).",
        "Misc",
        [
            {"step": 1, "priority": "normal", "icon": "bi-search", "title": "Identifier les groupes vides et auditer leurs ACLs",
             "detail": "Les groupes vides avec des ACE non-h\u00e9rit\u00e9es (GenericAll, AddMember) sont exploitables : un attaquant qui les contr\u00f4le peut y ajouter des comptes. Identifier les groupes vides ET v\u00e9rifier leurs permissions.",
             "commands": [{"label": "PowerShell \u2014 groupes vides avec ACLs dangereuses", "code": "$empty = Get-ADGroup -Filter * -Properties Members | Where-Object { $_.Members.Count -eq 0 }\nforeach ($g in $empty) {\n    $acl = Get-Acl \"AD:$($g.DistinguishedName)\"\n    $dangerous = $acl.Access | Where-Object {\n        $_.ActiveDirectoryRights -match 'GenericAll|WriteProperty|WriteDacl|WriteOwner' -and\n        $_.AccessControlType -eq 'Allow' -and\n        $_.IsInherited -eq $false\n    }\n    if ($dangerous) {\n        Write-Host \"[!] $($g.Name) a des ACE non-h\u00e9rit\u00e9es :\"\n        $dangerous | Select-Object IdentityReference, ActiveDirectoryRights\n    }\n}\n$empty | Select-Object Name, DistinguishedName | Export-Csv empty_groups.csv -NoTypeInformation"}]},
            {"step": 2, "priority": "normal", "icon": "bi-trash3", "title": "Supprimer ou archiver les groupes vides",
             "detail": "Apr\u00e8s confirmation qu'ils ne sont pas utilis\u00e9s, supprimer les groupes vides. Si incertain, les d\u00e9placer dans une OU Archive avec des permissions restreintes pendant une p\u00e9riode de gr\u00e2ce de 30 jours.",
             "commands": [{"label": "PowerShell \u2014 d\u00e9placer vers OU Archive", "code": "$archiveOU = 'OU=Archive_Groups,DC=domain,DC=com'\n$empty = Get-ADGroup -Filter * -Properties Members | Where-Object { $_.Members.Count -eq 0 }\nforeach ($g in $empty) {\n    Move-ADObject -Identity $g.DistinguishedName -TargetPath $archiveOU\n    Write-Host \"D\u00e9plac\u00e9 : $($g.Name)\"\n}\n\n# Apr\u00e8s la p\u00e9riode de gr\u00e3ce, supprimer :\n# Get-ADGroup -SearchBase $archiveOU -Filter * | Remove-ADGroup -Confirm:$false"}]},
        ]
    ),
    "empty_ous": (
        "Empty OUs",
        "Organizational Units with no objects.",
        "Misc",
        [
            {"step": 1, "priority": "normal", "icon": "bi-search", "title": "Identifier les OUs vides et leurs d\u00e9l\u00e9gations",
             "detail": "Les OUs vides avec des permissions d\u00e9l\u00e9gu\u00e9es sont un vecteur d'attaque : un attaquant qui les contr\u00f4le peut y cr\u00e9er des objets ou lier des GPOs malveillantes. Identifier ET auditer les ACLs.",
             "commands": [{"label": "PowerShell \u2014 OUs vides avec d\u00e9l\u00e9gations non-h\u00e9rit\u00e9es", "code": "$emptyOUs = Get-ADOrganizationalUnit -Filter * | Where-Object {\n    -not (Get-ADObject -Filter * -SearchBase $_.DistinguishedName -SearchScope OneLevel -ErrorAction SilentlyContinue)\n}\nforeach ($ou in $emptyOUs) {\n    $acl = Get-Acl \"AD:$($ou.DistinguishedName)\"\n    $delegated = $acl.Access | Where-Object { $_.IsInherited -eq $false -and $_.AccessControlType -eq 'Allow' }\n    if ($delegated) {\n        Write-Host \"[!] OU vide avec d\u00e9l\u00e9gations : $($ou.DistinguishedName)\"\n        $delegated | Select-Object IdentityReference, ActiveDirectoryRights\n    }\n}\n$emptyOUs | Select-Object Name, DistinguishedName | Export-Csv empty_ous.csv -NoTypeInformation"}]},
            {"step": 2, "priority": "normal", "icon": "bi-folder-x", "title": "Supprimer les d\u00e9l\u00e9gations et effacer les OUs vides",
             "detail": "Retirer les ACE non-standard avant suppression. D\u00e9sactiver la protection contre la suppression accidentelle si active, puis supprimer ou consolider les OUs.",
             "commands": [{"label": "PowerShell \u2014 supprimer les OUs vides (apr\u00e8s v\u00e9rification)", "code": "$emptyOUs = Get-ADOrganizationalUnit -Filter * | Where-Object {\n    -not (Get-ADObject -Filter * -SearchBase $_.DistinguishedName -SearchScope OneLevel -ErrorAction SilentlyContinue)\n}\n# ATTENTION : v\u00e9rifier la liste ci-dessous avant d'ex\u00e9cuter la suppression !\n$emptyOUs | Select-Object Name, DistinguishedName\n\n# Supprimer chaque OU vide :\nforeach ($ou in $emptyOUs) {\n    Set-ADOrganizationalUnit -Identity $ou.DistinguishedName -ProtectedFromAccidentalDeletion $false\n    Remove-ADOrganizationalUnit -Identity $ou.DistinguishedName -Confirm:$false\n    Write-Host \"Supprim\u00e9 : $($ou.Name)\"\n}"}]},
        ]
    ),
    "computers_list_of_rdp_users": (
        "RDP Users on Servers",
        "User accounts with RDP rights on servers.",
        "Network",
        [
            {"step": 1, "priority": "normal", "icon": "bi-search", "title": "Audit Remote Desktop Users on all servers",
             "detail": "Review membership of the Remote Desktop Users group on all servers.",
             "commands": [{"label": "PowerShell (multi-server)", "code": "$servers = Get-ADComputer -Filter {OperatingSystem -like '*Server*'} | Select-Object -ExpandProperty Name\nforeach ($s in $servers) {\n    try { $m = Invoke-Command -ComputerName $s {net localgroup 'Remote Desktop Users'} } catch { $m = 'unreachable' }\n    [pscustomobject]@{Server=$s; Members=$m}\n}"}]},
            {"step": 2, "priority": "normal", "icon": "bi-person-dash", "title": "Remove unnecessary RDP access",
             "detail": "Remove standard users from the Remote Desktop Users group on servers where they should not have access.",
             "commands": []},
        ]
    ),
}


def find_adminer_data_json(folder: str) -> str | None:
    """
    Search for data_*.json in the extracted AD-Miner folder.
    Returns the absolute path or None.
    """
    if not os.path.isdir(folder):
        return None
    for fname in os.listdir(folder):
        if fname.startswith("data_") and fname.endswith(".json"):
            candidate = os.path.join(folder, fname)
            if os.path.isfile(candidate):
                return candidate
    return None


def parse_adminer_data_json(filepath: str) -> dict:
    """
    Parse the AD-Miner data JSON and return a dict compatible with ADData + ADFinding.

    Returns:
        {
            "render_name":      str,
            "report_date":      str,
            "adminer_version":  str,
            # General stats (map to existing ADData fields)
            "domain_count":     int,
            "dc_count":         int,
            "domain_admin_count": int,
            "user_count":       int,
            "group_count":      int,
            "computer_count":   int,
            "adcs_count":       int,
            # Computed from color_category + value
            "kerberoastable_count":        int,
            "asreproastable_count":        int,
            "unconstrained_deleg_count":   int,
            "risk_rating":      str,   # CRITICAL / HIGH / MEDIUM / LOW / INFO
            "risk_score":       float, # 0–100
            # Raw data for storage
            "raw_values":       str,   # JSON string of the "value" dict
            "raw_color_category": str, # JSON string of the "color_category" dict
            # Findings (only indicators with color != green/grey and value > 0)
            "findings": [
                {
                    "category":       str,
                    "title":          str,
                    "severity":       str,
                    "description":    str,
                    "affected_count": int,
                    "details":        str,  # JSON "[]"
                },
                ...
            ]
        }
    """
    with open(filepath, "r", encoding="utf-8", errors="replace") as fh:
        data = json.load(fh)

    stats  = data.get("general_statistic", {})
    values = data.get("value", {})
    colors = data.get("color_category", {})

    render_name     = data.get("render_name", "")
    report_date     = data.get("datetime", "")
    adminer_version = data.get("AD_miner_version", "")

    # ── General stats ──────────────────────────────────────────────────────────
    domain_count        = int(stats.get("nb_domains",   0))
    dc_count            = int(stats.get("nb_dc",        0))
    domain_admin_count  = int(stats.get("nb_da",        0))
    user_count          = int(stats.get("nb_users",     0))
    group_count         = int(stats.get("nb_groups",    0))
    computer_count      = int(stats.get("nb_computers", 0))
    adcs_count          = int(stats.get("nb_adcs",      0))

    kerberoastable_count      = int(values.get("kerberoastables", 0))
    asreproastable_count      = int(values.get("as_rep",          0))
    unconstrained_deleg_count = int(values.get("non-dc_with_unconstrained_delegations", 0))

    # ── Risk rating ────────────────────────────────────────────────────────────
    # Count indicators at each color level where value > 0
    red_active    = sum(1 for k, c in colors.items() if c == "red"    and int(values.get(k, 0)) > 0)
    orange_active = sum(1 for k, c in colors.items() if c == "orange" and int(values.get(k, 0)) > 0)
    yellow_active = sum(1 for k, c in colors.items() if c == "yellow" and int(values.get(k, 0)) > 0)

    if red_active > 0:
        risk_rating = "CRITICAL"
    elif orange_active > 0:
        risk_rating = "HIGH"
    elif yellow_active > 0:
        risk_rating = "MEDIUM"
    else:
        risk_rating = "LOW"

    # Score 0-100: weighted by severity
    total = len([k for k in colors if colors[k] not in ("grey", None)])
    if total > 0:
        risk_score = min(100.0, round((red_active * 10 + orange_active * 5 + yellow_active * 2) / total * 10, 1))
    else:
        risk_score = 0.0

    # ── Build findings ─────────────────────────────────────────────────────────
    findings = []
    for key, color in colors.items():
        sev = _COLOR_TO_SEV.get(color)
        if sev is None or sev == "INFO":
            # Skip green (OK) and grey (N/A)
            continue

        count = int(values.get(key, 0))
        # Keep indicator even if count==0: AD-Miner assigns the color independently
        # of the raw count (e.g. a configuration risk with no affected objects).

        meta = _INDICATOR_META.get(key)
        if meta:
            title, description, category, remediation_steps = meta
        else:
            # Fallback: prettify key name
            title              = key.replace("_", " ").replace("-", " ").title()
            description        = f"AD-Miner indicator: {key}"
            category           = "Misc"
            remediation_steps  = []

        findings.append({
            "category":        category,
            "title":           title,
            "severity":        sev,
            "description":     description,
            "affected_count":  count,
            "details":         "[]",
            "remediation":     json.dumps(remediation_steps),
            "indicator_key":   key,
        })

    # Sort findings: CRITICAL first
    _sev_order = {"CRITICAL": 3, "HIGH": 2, "MEDIUM": 1}
    findings.sort(key=lambda f: _sev_order.get(f["severity"], 0), reverse=True)

    return {
        "render_name":             render_name,
        "report_date":             report_date,
        "adminer_version":         adminer_version,
        "domain_count":            domain_count,
        "dc_count":                dc_count,
        "domain_admin_count":      domain_admin_count,
        "user_count":              user_count,
        "group_count":             group_count,
        "computer_count":          computer_count,
        "adcs_count":              adcs_count,
        "kerberoastable_count":    kerberoastable_count,
        "asreproastable_count":    asreproastable_count,
        "unconstrained_deleg_count": unconstrained_deleg_count,
        "risk_rating":             risk_rating,
        "risk_score":              risk_score,
        "raw_values":              json.dumps(values),
        "raw_color_category":      json.dumps(colors),
        "findings":                findings,
    }
