"""
Parser for the AD-Miner data JSON file (data_<render_name>_<date>.json).

This file is generated by AD-Miner and embedded in its output ZIP. It contains:
  - general_statistic : nb_domains, nb_dc, nb_da, nb_users, nb_groups, nb_computers, nb_adcs
  - value             : 60+ indicator counters (kerberoastables, dangerous_paths, etc.)
  - color_category    : risk color per indicator (red/orange/yellow/green/grey)
  - render_name       : report title
  - datetime          : report date string
"""
import json
import os

# ── Severity mapping from AD-Miner color to internal severity ─────────────────
_COLOR_TO_SEV = {
    "red":    "CRITICAL",
    "orange": "HIGH",
    "yellow": "MEDIUM",
    "green":  "INFO",
    "grey":   None,   # skip
}

# ── Human-readable titles and descriptions per indicator key ──────────────────
_INDICATOR_META = {
    # RED - Immediate risk
    "dc_impersonation":                        ("DC Impersonation (Shadow Credentials)", "Domain Controllers vulnerable to shadow credentials attacks, allowing impersonation.", "Credentials / Authentication"),
    "up_to_date_admincount":                   ("Inadequate AdminCount Settings", "Objects with AdminCount=1 that should not have it, or vice versa.", "Permissions"),
    "dangerous_paths":                         ("Dangerous Attack Paths", "Attack paths leading to high-value targets (Domain Admins, DCs, etc.).", "Attack Paths"),
    "can_dcsync":                              ("DCSync Privilege",  "Non-DC accounts with replication rights allowing DCSync attacks.", "Permissions"),
    "ldap_configuration":                      ("LDAP Servers Configuration", "LDAP servers with insecure configuration (unsigned/unsigned LDAP binding).", "Network"),
    "objects_to_operators_member":             ("Paths to Operators Groups", "Objects with a path to built-in operator groups (Backup, Account, Print, etc.).", "Attack Paths"),
    "graph_path_objects_to_ou_handlers":       ("Paths to Organizational Units (OU)", "Objects that can modify GPOs or OUs affecting privileged accounts.", "Attack Paths"),
    "anomaly_acl":                             ("ACL Anomalies", "Abnormal or dangerous ACE entries on sensitive AD objects.", "Permissions"),
    # ORANGE - Alerts
    "rid_singularities":                       ("RID Singularities", "Accounts with suspicious RID values that may indicate legacy or rogue accounts.", "Misc"),
    "graph_path_objects_to_da":                ("Paths to Domain Admins", "Non-privileged objects with a direct or indirect path to Domain Admin privileges.", "Attack Paths"),
    "smb_signing":                             ("SMB Signing Disabled", "Computers without SMB signing enabled, vulnerable to relay attacks.", "Network"),
    "privileged_accounts_outside_Protected_Users": ("Privileged Accounts Outside Protected Users", "Privileged accounts not in the Protected Users group, reducing their protection.", "Credentials / Authentication"),
    "server_users_could_be_admin":             ("Users Who Could Become Admin on Servers", "Non-admin users who could escalate to admin on servers via misconfiguration.", "Permissions"),
    "users_admin_of_computers":                ("Non-Admin Users with Local Admin Rights", "Standard users holding local administrator rights on workstations or servers.", "Permissions"),
    # YELLOW - Minor risk
    "computers_without_laps":                  ("Computers Without LAPS", "Computers not managed by Local Administrator Password Solution.", "Credentials / Authentication"),
    "computers_last_connexion":                ("Stale Computer Accounts", "Computer accounts that have not connected in more than 90 days.", "Misc"),
    "dormants_accounts":                       ("Dormant User Accounts", "User accounts inactive for more than 90 days but still enabled.", "Misc"),
    "never_expires":                           ("Passwords That Never Expire", "User accounts with password set to never expire.", "Credentials / Authentication"),
    "pre_windows_2000_compatible_access_group": ("Pre-Windows 2000 Compatible Access Group", "Members of the legacy 'Pre-Windows 2000 Compatible Access' group with broad read rights.", "Permissions"),
    "users_pwd_not_changed_since":             ("Passwords Not Changed in 1+ Year", "User accounts whose password has not been changed for over a year.", "Credentials / Authentication"),
    # Less common indicators (may be green but map them anyway)
    "kerberoastables":                         ("Kerberoastable Accounts", "Service accounts with SPNs vulnerable to offline Kerberos ticket cracking.", "Kerberos"),
    "as_rep":                                  ("AS-REP Roastable Accounts", "Accounts with Kerberos pre-authentication disabled, vulnerable to AS-REP Roasting.", "Kerberos"),
    "non-dc_with_unconstrained_delegations":   ("Unconstrained Delegation (non-DC)", "Non-DC computers configured with unconstrained Kerberos delegation.", "Kerberos"),
    "users_constrained_delegations":           ("Constrained Delegation Users", "Users configured with constrained Kerberos delegation.", "Kerberos"),
    "has_sid_history":                         ("SID History Present", "Accounts with SID history that could be used for privilege escalation.", "Misc"),
    "vuln_permissions_adminsdholder":          ("AdminSDHolder Permission Anomalies", "Unexpected permissions on the AdminSDHolder container.", "Permissions"),
    "vuln_functional_level":                   ("Outdated Domain Functional Level", "Domain or forest functional level is below the current recommended standard.", "Misc"),
    "computers_os_obsolete":                   ("Obsolete Operating Systems", "Computers running end-of-life operating systems.", "Misc"),
    "can_read_laps":                           ("Unauthorized LAPS Password Readers", "Non-admin accounts that can read LAPS passwords.", "Credentials / Authentication"),
    "users_rdp_access":                        ("Excessive RDP Access", "Users with RDP access to systems they should not have access to.", "Network"),
    "unpriv_to_dnsadmins":                     ("Path to DNSAdmins", "Unprivileged accounts with a path to the DNSAdmins group.", "Attack Paths"),
    "dom_admin_on_non_dc":                     ("Domain Admins Logged On Non-DC", "Domain admin sessions detected on non-domain-controller machines.", "Credentials / Authentication"),
    "users_pwd_cleartext":                     ("Passwords in Cleartext", "Accounts storing or transmitting passwords in cleartext.", "Credentials / Authentication"),
    "empty_groups":                            ("Empty Groups", "Security groups with no members (may indicate orphaned groups).", "Misc"),
    "empty_ous":                               ("Empty OUs", "Organizational Units with no objects.", "Misc"),
    "computers_list_of_rdp_users":             ("RDP Users on Servers", "User accounts with RDP rights on servers.", "Network"),
    "guest_accounts":                          ("Active Guest Accounts", "Guest accounts that are enabled.", "Credentials / Authentication"),
    "users_password_not_required":             ("Accounts Without Password Requirement", "Accounts where a password is not required to log in.", "Credentials / Authentication"),
    "objects_to_adcs":                         ("Paths to ADCS", "Objects with paths to Active Directory Certificate Services.", "Attack Paths"),
    "cross_domain_admin_privileges":           ("Cross-Domain Admin Privileges", "Accounts with administrative privileges spanning multiple domains.", "Permissions"),
    "users_shadow_credentials":                ("Shadow Credentials on Users", "Users with shadow credentials set, allowing impersonation.", "Credentials / Authentication"),
    "users_shadow_credentials_to_non_admins":  ("Shadow Credentials Targeting Non-Admins", "Shadow credentials set on non-privileged accounts.", "Credentials / Authentication"),
    "can_read_gmsapassword_of_adm":            ("Unauthorized gMSA Password Readers", "Accounts that can read the gMSA password of privileged accounts.", "Credentials / Authentication"),
    "users_GPO_access":                        ("Excessive GPO Write Access", "Users with write access to Group Policy Objects.", "Permissions"),
    "computers_members_high_privilege":        ("Computers in High-Privilege Groups", "Computer accounts that are members of high-privilege groups.", "Permissions"),
    "graph_list_objects_rbcd":                 ("Resource-Based Constrained Delegation (RBCD)", "Objects configured with RBCD that could allow privilege escalation.", "Kerberos"),
    "computer_admin_of_computers":             ("Computer Accounts Admin of Computers", "Computer accounts with admin rights on other computers.", "Permissions"),
    "da_to_da":                                ("DA-to-DA Trust Paths", "Paths between Domain Admin accounts across domains.", "Attack Paths"),
    "krb_last_change":                         ("Stale KRBTGT Password", "KRBTGT account password not changed in over 180 days.", "Kerberos"),
    "fgpp":                                    ("Fine-Grained Password Policies", "Fine-grained password policies configured in the domain.", "Credentials / Authentication"),
    "nb_domain_admins":                        ("Number of Domain Admins", "Total count of Domain Admin accounts.", "Misc"),
}


def find_adminer_data_json(folder: str) -> str | None:
    """
    Search for data_*.json in the extracted AD-Miner folder.
    Returns the absolute path or None.
    """
    if not os.path.isdir(folder):
        return None
    for fname in os.listdir(folder):
        if fname.startswith("data_") and fname.endswith(".json"):
            candidate = os.path.join(folder, fname)
            if os.path.isfile(candidate):
                return candidate
    return None


def parse_adminer_data_json(filepath: str) -> dict:
    """
    Parse the AD-Miner data JSON and return a dict compatible with ADData + ADFinding.

    Returns:
        {
            "render_name":      str,
            "report_date":      str,
            "adminer_version":  str,
            # General stats (map to existing ADData fields)
            "domain_count":     int,
            "dc_count":         int,
            "domain_admin_count": int,
            "user_count":       int,
            "group_count":      int,
            "computer_count":   int,
            "adcs_count":       int,
            # Computed from color_category + value
            "kerberoastable_count":        int,
            "asreproastable_count":        int,
            "unconstrained_deleg_count":   int,
            "risk_rating":      str,   # CRITICAL / HIGH / MEDIUM / LOW / INFO
            "risk_score":       float, # 0–100
            # Raw data for storage
            "raw_values":       str,   # JSON string of the "value" dict
            "raw_color_category": str, # JSON string of the "color_category" dict
            # Findings (only indicators with color != green/grey and value > 0)
            "findings": [
                {
                    "category":       str,
                    "title":          str,
                    "severity":       str,
                    "description":    str,
                    "affected_count": int,
                    "details":        str,  # JSON "[]"
                },
                ...
            ]
        }
    """
    with open(filepath, "r", encoding="utf-8", errors="replace") as fh:
        data = json.load(fh)

    stats  = data.get("general_statistic", {})
    values = data.get("value", {})
    colors = data.get("color_category", {})

    render_name     = data.get("render_name", "")
    report_date     = data.get("datetime", "")
    adminer_version = data.get("AD_miner_version", "")

    # ── General stats ──────────────────────────────────────────────────────────
    domain_count        = int(stats.get("nb_domains",   0))
    dc_count            = int(stats.get("nb_dc",        0))
    domain_admin_count  = int(stats.get("nb_da",        0))
    user_count          = int(stats.get("nb_users",     0))
    group_count         = int(stats.get("nb_groups",    0))
    computer_count      = int(stats.get("nb_computers", 0))
    adcs_count          = int(stats.get("nb_adcs",      0))

    kerberoastable_count      = int(values.get("kerberoastables", 0))
    asreproastable_count      = int(values.get("as_rep",          0))
    unconstrained_deleg_count = int(values.get("non-dc_with_unconstrained_delegations", 0))

    # ── Risk rating ────────────────────────────────────────────────────────────
    # Count indicators at each color level where value > 0
    red_active    = sum(1 for k, c in colors.items() if c == "red"    and int(values.get(k, 0)) > 0)
    orange_active = sum(1 for k, c in colors.items() if c == "orange" and int(values.get(k, 0)) > 0)
    yellow_active = sum(1 for k, c in colors.items() if c == "yellow" and int(values.get(k, 0)) > 0)

    if red_active > 0:
        risk_rating = "CRITICAL"
    elif orange_active > 0:
        risk_rating = "HIGH"
    elif yellow_active > 0:
        risk_rating = "MEDIUM"
    else:
        risk_rating = "LOW"

    # Score 0-100: weighted by severity
    total = len([k for k in colors if colors[k] not in ("grey", None)])
    if total > 0:
        risk_score = min(100.0, round((red_active * 10 + orange_active * 5 + yellow_active * 2) / total * 10, 1))
    else:
        risk_score = 0.0

    # ── Build findings ─────────────────────────────────────────────────────────
    findings = []
    for key, color in colors.items():
        sev = _COLOR_TO_SEV.get(color)
        if sev is None or sev == "INFO":
            # Skip green (OK) and grey (N/A)
            continue

        count = int(values.get(key, 0))
        if count == 0:
            continue  # Only report active indicators

        meta = _INDICATOR_META.get(key)
        if meta:
            title, description, category = meta
        else:
            # Fallback: prettify key name
            title       = key.replace("_", " ").replace("-", " ").title()
            description = f"AD-Miner indicator: {key}"
            category    = "Misc"

        findings.append({
            "category":       category,
            "title":          title,
            "severity":       sev,
            "description":    description,
            "affected_count": count,
            "details":        "[]",
        })

    # Sort findings: CRITICAL first
    _sev_order = {"CRITICAL": 3, "HIGH": 2, "MEDIUM": 1}
    findings.sort(key=lambda f: _sev_order.get(f["severity"], 0), reverse=True)

    return {
        "render_name":             render_name,
        "report_date":             report_date,
        "adminer_version":         adminer_version,
        "domain_count":            domain_count,
        "dc_count":                dc_count,
        "domain_admin_count":      domain_admin_count,
        "user_count":              user_count,
        "group_count":             group_count,
        "computer_count":          computer_count,
        "adcs_count":              adcs_count,
        "kerberoastable_count":    kerberoastable_count,
        "asreproastable_count":    asreproastable_count,
        "unconstrained_deleg_count": unconstrained_deleg_count,
        "risk_rating":             risk_rating,
        "risk_score":              risk_score,
        "raw_values":              json.dumps(values),
        "raw_color_category":      json.dumps(colors),
        "findings":                findings,
    }
